'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import Image from 'next/image';
import StatsStrip from '@/components/StatsStrip';
import CompanySection from '@/components/CompanySection';
import {
  ChevronDown,
  Scale,
  ExternalLink,
  ShieldCheck,
  CheckCircle2,
  AlertTriangle,
  FileText,
  HelpCircle,
  TrendingUp,
  Award,
  BookOpen,
  Building2,
  DollarSign,
  Check,
  Lock,
  Phone,
  AlertCircle,
  CreditCard,
  Briefcase,
  Bookmark,
  ArrowRight,
  Clock,
  UserCheck,
  Sparkles,
  Gavel,
  BadgeAlert,
  Landmark,
  ShieldAlert,
  MessageSquareWarning,
  SearchCheck
} from 'lucide-react';

export default function FakeLegalNoticeFromAdvocateWhatsappClient() {
  const [activeId, setActiveId] = useState<string>('quick-crux');
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
          }
        });
      },
      {
        rootMargin: '-100px 0px -40% 0px',
        threshold: 0.05
      }
    );

    const headings = document.querySelectorAll('section[id], div[id].scroll-target');
    headings.forEach((heading) => observer.observe(heading));

    return () => {
      headings.forEach((heading) => observer.unobserve(heading));
    };
  }, []);

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const navLinks = [
    { id: 'quick-crux', label: 'Executive Brief & Crux' },
    { id: 'whatsapp-legal-notice-scam', label: '1. WhatsApp Notice Scams' },
    { id: 'how-to-spot-fake-notices', label: '2. Forensic Red Flags' },
    { id: 'legal-notice-comparison-matrix', label: '3. Notice vs Summons Matrix' },
    { id: 'statutory-laws-and-penalties', label: '4. Criminal Laws & Penalties' },
    { id: 'infographic-overview', label: 'Visual Verification Blueprint' },
    { id: 'step-by-step-verification-sop', label: '5. 6-Stage Verification SOP' },
    { id: 'borrower-rights-and-protections', label: '6. Borrower Legal Protections' },
    { id: 'three-tier-escalation-matrix', label: '7. 3-Tier Escalation Plan' },
    { id: 'chronological-dispute-timeline', label: '8. Dispute Resolution Timeline' },
    { id: 'specialized-fraud-scenarios', label: '9. Loan Apps & Scenarios' },
    { id: 'company-profile', label: 'About CredSettle' },
    { id: 'frequently-asked-questions', label: 'Frequently Asked Questions' },
    { id: 'regulatory-sources', label: 'Statutory Citations' }
  ];

  const faqs = [
    {
      q: 'Can an advocate send a legally valid legal notice via WhatsApp in India?',
      a: 'While the Supreme Court recognized digital service via WhatsApp and email, a valid notice must originate from an enrolled advocate with verifiable Bar Council credentials, chamber address, and signature. Recovery agents sending unauthorized PDF threat letters on WhatsApp commit unlawful extortion and forgery.'
    },
    {
      q: 'How can I verify if an advocate who sent a WhatsApp notice is real or fake?',
      a: 'Check the advocate\'s Bar Council enrollment number (e.g., D/1234/2019) on the respective State Bar Council directory. If the notice lacks an active enrollment number, official physical address, or working landline, it is a fabricated notice generated by a third-party recovery agency.'
    },
    {
      q: 'Can police arrest me immediately based on a WhatsApp legal notice or FIR copy?',
      a: 'No. Police cannot arrest you over WhatsApp messages. Unsecured loan default is a civil dispute under the Indian Contract Act. Police do not register FIRs for genuine loan defaults, and official summons or warrants must be served physically by authorized personnel.'
    },
    {
      q: 'What should I do immediately after receiving a threatening legal notice on WhatsApp?',
      a: 'Preserve all chat screenshots, sender numbers, and PDF files. Do not transfer funds to arbitrary UPI handles. Consult a debt resolution specialist to verify lawyer credentials and e-Courts records, then escalate to the bank Nodal Officer and Cyber Crime portal.'
    },
    {
      q: 'Is it illegal for recovery agents to send forged court summons or police seals on WhatsApp?',
      a: 'Yes. Forging judicial emblems, magistrate signatures, or police seals constitutes severe non-bailable forgery under Section 336 and 340 BNS (erstwhile Sections 463/471 IPC) and Section 66D IT Act for digital impersonation, carrying penalties up to seven years imprisonment.'
    },
    {
      q: 'Can a bank or NBFC send a legal notice directly without involving an advocate?',
      a: 'Banks can issue internal recall or demand letters on company letterhead. However, a formal "Legal Notice" can only be drafted and served by an advocate licensed under the Advocates Act, 1961. Unsigned demand notices titled "Legal Notice" lack judicial standing.'
    },
    {
      q: 'How do I check if a case mentioned in the WhatsApp notice is actually filed in court?',
      a: 'Search the 16-digit Case Navigation Record (CNR) number or party name on the official e-Courts Services portal (services.ecourts.gov.in). If no record appears in the district court registry, the case number and hearing dates cited in the notice are completely fabricated.'
    },
    {
      q: 'What is the difference between a genuine Section 138 notice and a fake WhatsApp threat?',
      a: 'A genuine Section 138 NI Act notice gives a mandatory statutory 15-day repayment window and is served via registered post following cheque dishonor. Fake WhatsApp notices demand immediate payment within hours, threaten instant police raids, and omit statutory timelines.'
    },
    {
      q: 'Can I file a police complaint or cyber crime report against recovery agents sending fake notices?',
      a: 'Yes. Lodge a formal cyber fraud complaint on the National Cyber Crime Reporting Portal (cybercrime.gov.in) under Section 66D IT Act and relevant BNS extortion provisions. You should also escalate the matter to the lending institution\'s Nodal Officer and RBI Ombudsman.'
    },
    {
      q: 'Can I still settle my loan if the bank or recovery agency sent fake legal notices?',
      a: 'Yes. Rogue recovery tactics give you significant regulatory leverage. You can demand action against abusive agencies while negotiating a structured One-Time Settlement (OTS) with the bank Credit Committee for a 40% to 60% principal waiver with a formal No Dues Certificate.'
    }
  ];

  return (
    <main className="min-h-screen bg-slate-50 text-slate-900 selection:bg-[#1886ff] selection:text-white">
      {/* 1. HERO SECTION (#2452ae Background) */}
      <section
        className="relative text-white pt-14 pb-10 md:pt-18 md:pb-12 px-4 md:px-8 overflow-hidden flex items-center justify-center text-center"
        style={{ backgroundColor: '#2452ae' }}
      >
        <div className="absolute inset-0 bg-black/5 z-0 pointer-events-none" />
        <div className="max-w-5xl mx-auto text-center z-10 relative">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-white text-xs font-semibold uppercase tracking-wider mb-4 border border-white/20">
            <ShieldAlert className="w-3.5 h-3.5 text-blue-200" />
            <span>Digital Fraud Defense &amp; Notice Verification</span>
          </div>

          <h1 className="text-2xl sm:text-3xl md:text-4xl lg:text-5xl font-extrabold mb-3 md:mb-4 tracking-tight leading-tight drop-shadow-xs">
            Fake Legal Notice on WhatsApp? How to Verify &amp; Reply
          </h1>

          <p className="text-sm sm:text-base md:text-lg mb-5 md:mb-6 max-w-2xl mx-auto font-normal text-white/95 leading-relaxed">
            Received an intimidating WhatsApp notice claiming to be an advocate letter, police FIR, or court summons? Learn how collection agencies forge seals, verify genuine Bar Council credentials, and protect your rights with CredSettle.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/contact"
              className="px-7 py-3 md:px-8 md:py-3.5 rounded-full bg-white text-blue-900 hover:text-[#1886ff] font-extrabold text-sm md:text-base hover:bg-slate-50 transition-all shadow-lg hover:shadow-xl transform hover:-translate-y-0.5 inline-flex items-center justify-center gap-2"
            >
              <span>Verify Your Legal Notice Today</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      {/* 2. STATS STRIP COMPONENT */}
      <StatsStrip />

      {/* 3. WIDESCREEN 3-COLUMN LAYOUT */}
      <div className="w-full max-w-[1720px] mx-auto px-4 md:px-8 py-8 md:py-12">
        <div className="grid grid-cols-1 lg:grid-cols-[240px_minmax(0,1fr)_280px] xl:grid-cols-[260px_minmax(0,1fr)_300px] 2xl:grid-cols-[280px_minmax(0,1fr)_320px] gap-5 xl:gap-6 items-start">
          
          {/* ================= LEFT COLUMN: STICKY TOC ================= */}
          <aside className="sticky top-6 hidden lg:block">
            <div className="bg-white rounded-2xl border border-slate-200/80 shadow-xs p-4 overflow-hidden">
              <div className="flex items-center gap-2 pb-3 mb-3 border-b border-slate-100">
                <BookOpen className="w-4 h-4 text-[#1886ff]" />
                <span className="text-xs font-black uppercase tracking-wider text-slate-800">
                  Table of Contents
                </span>
              </div>
              <nav className="space-y-1 max-h-[calc(100vh-140px)] overflow-y-auto pr-1 text-xs">
                {navLinks.map((link) => {
                  const isActive = activeId === link.id;
                  return (
                    <a
                      key={link.id}
                      href={`#${link.id}`}
                      className={`group flex items-center justify-between px-3 py-2 rounded-xl transition-all font-medium leading-snug ${
                        isActive
                          ? 'bg-blue-50 text-[#1886ff] font-bold shadow-2xs'
                          : 'text-slate-600 hover:bg-slate-50 hover:text-slate-900'
                      }`}
                    >
                      <span className="truncate mr-2">{link.label}</span>
                      <ChevronDown
                        className={`w-3 h-3 flex-shrink-0 transition-transform ${
                          isActive ? '-rotate-90 text-[#1886ff]' : 'opacity-0 group-hover:opacity-40'
                        }`}
                      />
                    </a>
                  );
                })}
              </nav>
            </div>
          </aside>

          {/* ================= CENTER COLUMN: EDITORIAL CONTENT ================= */}
          <article className="space-y-8 md:space-y-10 min-w-0">
            
            {/* EXECUTIVE SUMMARY BOX */}
            <div
              id="quick-crux"
              className="scroll-target rounded-2xl p-5 md:p-6 bg-[#F4F8FE] border-l-[5px] border-l-[#1886ff] border border-blue-100/80 shadow-xs"
            >
              <div className="flex items-center gap-2 pb-3 mb-3 border-b border-blue-100">
                <ShieldCheck className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-base sm:text-lg font-bold text-slate-900">
                  Executive Brief: WhatsApp Legal Notices
                </h2>
              </div>
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2.5 text-xs sm:text-sm text-slate-700">
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#1886ff] flex-shrink-0" />
                  <span>Call center agents masquerading as High Court advocates.</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#1886ff] flex-shrink-0" />
                  <span>Forged court seals and police emblems constitute criminal forgery.</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#1886ff] flex-shrink-0" />
                  <span>Urgent 2-hour payment demands violate statutory 15-day notice rules.</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#1886ff] flex-shrink-0" />
                  <span>Personal UPI IDs and QR codes indicate unauthorized recovery extortion.</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#1886ff] flex-shrink-0" />
                  <span>Instant verification via State Bar Council and e-Courts CNR records.</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#1886ff] flex-shrink-0" />
                  <span>Direct criminal penalties under Section 66D Information Technology Act.</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#1886ff] flex-shrink-0" />
                  <span>Formal regulatory escalation to Bank Nodal Officers and RBI Ombudsman.</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#1886ff] flex-shrink-0" />
                  <span>Structured One-Time Settlement (OTS) waivers between 40% and 60%.</span>
                </div>
              </div>
            </div>

            {/* SECTION 1: THE PHENOMENON OF FAKE WHATSAPP NOTICES */}
            <section id="whatsapp-legal-notice-scam" className="scroll-target space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <Scale className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  1. The WhatsApp Legal Notice Scam: Why Recovery Agents Use Digital Deception
                </h2>
              </div>

              <p className="text-sm sm:text-base leading-relaxed text-slate-700">
                When an unsecured personal loan, credit card, or digital loan defaults, financial institutions frequently assign delinquent accounts to third-party recovery agencies. Operating on aggressive commission targets, these outsourced agents often abandon lawful collection methods and deploy deceptive WhatsApp messages containing fabricated legal notices, police FIR copies, or fake court summons.
              </p>

              <p className="text-sm sm:text-base leading-relaxed text-slate-700">
                Filing civil suits or criminal complaints under Section 138 of the Negotiable Instruments Act requires lenders to pay court fees, engage advocates, and follow strict judicial timelines. For unsecured debts, formal court litigation is often slow and expensive. Consequently, collection agents use WhatsApp to deliver menacing PDF attachments with forged court headers and arrest threats to trigger immediate borrower panic without judicial scrutiny.
              </p>
            </section>

            {/* SECTION 2: FORENSIC ANATOMY OF FRAUDULENT NOTICES & RED FLAGS */}
            <section id="how-to-spot-fake-notices" className="scroll-target space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <SearchCheck className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  2. Forensic Anatomy of a Fake Notice: Key Red Flags to Identify
                </h2>
              </div>

              <p className="text-sm sm:text-base leading-relaxed text-slate-700">
                Genuine legal notices drafted by practicing Indian advocates comply with the Advocates Act, 1961, and Bar Council regulations. In contrast, fraudulent digital notices display several unmistakable forensic errors:
              </p>

              <div className="space-y-3 text-sm text-slate-700">
                <p className="leading-relaxed">
                  <strong>Missing Bar Council Enrollment:</strong> Every licensed advocate possesses a state Bar Council registration code (such as D/1234/2019). Fake notices omit this number, list burner mobile numbers, or invent fictional designations like &quot;Chief Legal Officer of Recovery&quot;.
                </p>
                <p className="leading-relaxed">
                  <strong>Unrealistic Deadlines &amp; Arrest Threats:</strong> Authentic Section 138 notices grant a statutory 15-day repayment window. Fraudulent notices demand settlement within two hours and threaten immediate non-bailable arrest under Section 420 IPC (Section 318 BNS), which is legally impossible for pure civil debt defaults.
                </p>
                <p className="leading-relaxed">
                  <strong>Personal UPI Handles:</strong> Fake notices often include QR codes or personal UPI handles. Legitimate banks and NBFCs only accept payments credited directly to the borrower&apos;s verified loan account number.
                </p>
              </div>
            </section>

            {/* SECTION 3: 4-SIDED BORDERED COMPARISON MATRIX */}
            <section id="legal-notice-comparison-matrix" className="scroll-target space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <Gavel className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  3. Comparative Matrix: Fake Notices vs Genuine Legal Instruments
                </h2>
              </div>

              <p className="text-sm sm:text-base leading-relaxed text-slate-700">
                Distinguishing between authentic court summons, lawful advocate demand notices, and fraudulent WhatsApp extortion messages is critical for executing an effective legal response.
              </p>

              <div className="border border-slate-200/80 rounded-2xl overflow-x-auto shadow-xs bg-white">
                <table className="w-full text-left text-xs sm:text-sm divide-y divide-slate-200/80">
                  <thead className="bg-slate-50 text-slate-800 font-bold">
                    <tr className="divide-x divide-slate-200/80">
                      <th className="px-3.5 py-3 font-extrabold text-[#0C2756]">Notice Type</th>
                      <th className="px-3.5 py-3">Issuing Authority</th>
                      <th className="px-3.5 py-3">Delivery Medium</th>
                      <th className="px-3.5 py-3">Legal Enforceability</th>
                      <th className="px-3.5 py-3">Required Action</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200/80 text-slate-700 font-normal">
                    <tr className="divide-x divide-slate-200/80 bg-rose-50/40 hover:bg-rose-50/60">
                      <td className="px-3.5 py-2.5 font-bold text-rose-700">Fake WhatsApp Notice</td>
                      <td className="px-3.5 py-2.5">Unauthorized Collection Agency</td>
                      <td className="px-3.5 py-2.5">WhatsApp PDF / Image</td>
                      <td className="px-3.5 py-2.5 font-semibold text-rose-700">Zero (Criminal Forgery)</td>
                      <td className="px-3.5 py-2.5">File Cyber Crime &amp; RBI Complaints</td>
                    </tr>
                    <tr className="divide-x divide-slate-200/80 hover:bg-slate-50/60">
                      <td className="px-3.5 py-2.5 font-bold text-slate-900">Advocate Demand Notice</td>
                      <td className="px-3.5 py-2.5">Enrolled Bar Council Lawyer</td>
                      <td className="px-3.5 py-2.5">Registered Post / Verified Email</td>
                      <td className="px-3.5 py-2.5 font-semibold text-amber-700">Pre-Litigation Demand</td>
                      <td className="px-3.5 py-2.5">Serve Legal Reply &amp; Initiate OTS</td>
                    </tr>
                    <tr className="divide-x divide-slate-200/80 bg-blue-50/30 hover:bg-blue-50/50">
                      <td className="px-3.5 py-2.5 font-bold text-[#1886ff]">Magistrate Court Summons</td>
                      <td className="px-3.5 py-2.5">Judicial Magistrate / Civil Court</td>
                      <td className="px-3.5 py-2.5">Court Bailiff / Speed Post</td>
                      <td className="px-3.5 py-2.5 font-bold text-emerald-700">Statutory Judicial Order</td>
                      <td className="px-3.5 py-2.5">Enter Appearance via Defense Counsel</td>
                    </tr>
                    <tr className="divide-x divide-slate-200/80 hover:bg-slate-50/60">
                      <td className="px-3.5 py-2.5 font-bold text-purple-900">Police Summons (41A CrPC)</td>
                      <td className="px-3.5 py-2.5">Police Investigating Officer</td>
                      <td className="px-3.5 py-2.5">Physical Notice with Police Seal</td>
                      <td className="px-3.5 py-2.5 font-semibold text-purple-800">Statutory Inquiry Order</td>
                      <td className="px-3.5 py-2.5">Attend with Counsel or Submit Reply</td>
                    </tr>
                    <tr className="divide-x divide-slate-200/80 hover:bg-slate-50/60">
                      <td className="px-3.5 py-2.5 font-bold text-emerald-800">Bank OTS Offer Letter</td>
                      <td className="px-3.5 py-2.5">Authorized Credit Committee</td>
                      <td className="px-3.5 py-2.5">Official Bank Domain Email</td>
                      <td className="px-3.5 py-2.5 font-bold text-emerald-700">Binding Settlement Contract</td>
                      <td className="px-3.5 py-2.5">Verify Terms &amp; Remit Settlement Sum</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>

            {/* SECTION 4: CRIMINAL LAWS & CYBER STATUTES */}
            <section id="statutory-laws-and-penalties" className="scroll-target space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <Landmark className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  4. Statutory Penalties: Criminal Liabilities for Sending Fake Notices
                </h2>
              </div>

              <p className="text-sm sm:text-base leading-relaxed text-slate-700">
                When a recovery agent forges court emblems, impersonates an advocate, or threatens unlawful arrest, the agent and the lending institution incur direct criminal liability under Indian law:
              </p>

              <div className="space-y-3 text-sm text-slate-700">
                <p className="leading-relaxed">
                  <strong>Bharatiya Nyaya Sanhita (BNS):</strong> Section 336 and 340 BNS punish document and judicial seal forgery with up to seven years imprisonment. Section 319 BNS penalizes public servant impersonation with rigorous jail terms.
                </p>
                <p className="leading-relaxed">
                  <strong>Information Technology Act:</strong> Section 66D of the IT Act penalizes cheating by personation via computer resources or messaging apps with up to three years imprisonment and monetary fines.
                </p>
                <p className="leading-relaxed">
                  <strong>Advocates Act &amp; RBI Directives:</strong> Section 29 of the Advocates Act restricts legal practice exclusively to enrolled lawyers. Furthermore, RBI Fair Practices Code and Digital Lending Guidelines strictly prohibit misleading legal representations and borrower harassment.
                </p>
              </div>
            </section>

            {/* SECTION 5: INFOGRAPHIC CARD */}
            <section id="infographic-overview" className="scroll-target space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <Sparkles className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  Infographic: 4-Step Verification Blueprint for WhatsApp Notices
                </h2>
              </div>

              <p className="text-sm sm:text-base leading-relaxed text-slate-700">
                This structured visual defense guide details the four sequential steps to verify advocate credentials, detect forged judicial seals, check national e-Courts records, and file cyber fraud complaints.
              </p>

              <div className="rounded-2xl border border-slate-200/90 overflow-hidden bg-slate-900 shadow-md">
                <div className="relative aspect-video w-full bg-slate-950">
                  <Image
                    src="/images/infographics/fake-legal-notice-from-advocate-whatsapp.jpg"
                    alt="How to Spot and Verify Fake Legal Notices on WhatsApp Infographic Blueprint"
                    fill
                    priority
                    sizes="(max-width: 1200px) 100vw, 900px"
                    className="object-cover"
                  />
                </div>
                <div className="p-3.5 bg-slate-900 text-slate-300 flex flex-wrap items-center justify-between gap-2 text-xs">
                  <span>Figure 1: CredSettle 4-Step WhatsApp Notice Verification &amp; Cyber Defense Protocol</span>
                  <a
                    href="/images/infographics/fake-legal-notice-from-advocate-whatsapp.jpg"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="text-[#1886ff] hover:underline font-semibold inline-flex items-center gap-1"
                  >
                    <span>View High-Res Infographic</span>
                    <ExternalLink className="w-3 h-3" />
                  </a>
                </div>
              </div>
            </section>

            {/* SECTION 6: STEP-BY-STEP SOP (6 STAGES) */}
            <section id="step-by-step-verification-sop" className="scroll-target space-y-5">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <Award className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  5. Step-by-Step SOP: How to Verify, Reply, and Neutralize Fake Notices
                </h2>
              </div>

              <p className="text-sm sm:text-base leading-relaxed text-slate-700">
                CredSettle executes a systematic six-stage Standard Operating Procedure to audit disputed notices, shield borrowers from harassment, and achieve formal debt resolution.
              </p>

              <div className="space-y-4">
                <div className="bg-white rounded-2xl border border-slate-200/80 p-4 sm:p-5 shadow-2xs">
                  <div className="flex items-center gap-3 mb-2">
                    <span className="w-7 h-7 rounded-lg bg-blue-100 text-[#1886ff] font-extrabold flex items-center justify-center text-xs">01</span>
                    <h3 className="text-base font-bold text-slate-900">Stage 1: Bar Council Credential Audit</h3>
                  </div>
                  <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
                    We verify the lawyer name and enrollment number against state Bar Council directories. If the sender is unverified or unregistered, we document the impersonation for legal escalation.
                  </p>
                </div>

                <div className="bg-white rounded-2xl border border-slate-200/80 p-4 sm:p-5 shadow-2xs">
                  <div className="flex items-center gap-3 mb-2">
                    <span className="w-7 h-7 rounded-lg bg-blue-100 text-[#1886ff] font-extrabold flex items-center justify-center text-xs">02</span>
                    <h3 className="text-base font-bold text-slate-900">Stage 2: e-Courts CNR Docket Verification</h3>
                  </div>
                  <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
                    If litigation is claimed, our advocates check the 16-digit CNR number on the national e-Courts portal. If no docket exists, the court case claim is confirmed to be fraudulent.
                  </p>
                </div>

                <div className="bg-white rounded-2xl border border-slate-200/80 p-4 sm:p-5 shadow-2xs">
                  <div className="flex items-center gap-3 mb-2">
                    <span className="w-7 h-7 rounded-lg bg-blue-100 text-[#1886ff] font-extrabold flex items-center justify-center text-xs">03</span>
                    <h3 className="text-base font-bold text-slate-900">Stage 3: Evidence Archiving &amp; Metadata Preservation</h3>
                  </div>
                  <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
                    We secure complete digital exports of the WhatsApp chat, including timestamped screenshots, sender profile data, attached PDFs, and audio recordings of threatening calls.
                  </p>
                </div>

                <div className="bg-white rounded-2xl border border-slate-200/80 p-4 sm:p-5 shadow-2xs">
                  <div className="flex items-center gap-3 mb-2">
                    <span className="w-7 h-7 rounded-lg bg-blue-100 text-[#1886ff] font-extrabold flex items-center justify-center text-xs">04</span>
                    <h3 className="text-base font-bold text-slate-900">Stage 4: Formal Cease-and-Desist Legal Reply</h3>
                  </div>
                  <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
                    CredSettle advocates serve a formal legal reply and cease-and-desist notice to the lender and collection agency, refuting false claims and demanding an immediate end to unlawful threats.
                  </p>
                </div>

                <div className="bg-white rounded-2xl border border-slate-200/80 p-4 sm:p-5 shadow-2xs">
                  <div className="flex items-center gap-3 mb-2">
                    <span className="w-7 h-7 rounded-lg bg-blue-100 text-[#1886ff] font-extrabold flex items-center justify-center text-xs">05</span>
                    <h3 className="text-base font-bold text-slate-900">Stage 5: RBI Ombudsman &amp; Cyber Police Escalation</h3>
                  </div>
                  <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
                    If harassment continues, we submit complaints to the National Cyber Crime Portal (cybercrime.gov.in) and the RBI Integrated Ombudsman (cms.rbi.org.in), triggering regulatory action.
                  </p>
                </div>

                <div className="bg-white rounded-2xl border border-slate-200/80 p-4 sm:p-5 shadow-2xs">
                  <div className="flex items-center gap-3 mb-2">
                    <span className="w-7 h-7 rounded-lg bg-blue-100 text-[#1886ff] font-extrabold flex items-center justify-center text-xs">06</span>
                    <h3 className="text-base font-bold text-slate-900">Stage 6: Bilateral OTS Negotiations &amp; Closure</h3>
                  </div>
                  <p className="text-xs sm:text-sm leading-relaxed text-slate-600">
                    Using regulatory violations as negotiation leverage, CredSettle engages the bank Credit Committee directly, securing a 40% to 60% principal waiver and an unconditional No Dues Certificate.
                  </p>
                </div>
              </div>
            </section>

            {/* SECTION 7: STATUTORY NOTICE DEFENSE & BORROWER RIGHTS */}
            <section id="borrower-rights-and-protections" className="scroll-target space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <BadgeAlert className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  6. Statutory Protections: Borrower Rights Under Indian Law
                </h2>
              </div>

              <p className="text-sm sm:text-base leading-relaxed text-slate-700">
                Under the Constitution of India and RBI directives, borrowers in financial distress possess statutory protections against unlawful debt collection practices:
              </p>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
                <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-2xs space-y-1.5">
                  <div className="flex items-center gap-2 text-slate-900 font-bold text-sm">
                    <ShieldCheck className="w-4 h-4 text-[#1886ff]" />
                    <span>1. Protection from Harassment</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    Article 21 and RBI Fair Practices rules strictly prohibit collection agents from using abusive language, threatening physical harm, or simulating police arrests.
                  </p>
                </div>

                <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-2xs space-y-1.5">
                  <div className="flex items-center gap-2 text-slate-900 font-bold text-sm">
                    <Lock className="w-4 h-4 text-emerald-600" />
                    <span>2. Right to Data Privacy</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    Lenders cannot contact family members, employers, or third-party references regarding debt defaults under the Digital Personal Data Protection Act, 2023.
                  </p>
                </div>

                <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-2xs space-y-1.5">
                  <div className="flex items-center gap-2 text-slate-900 font-bold text-sm">
                    <Scale className="w-4 h-4 text-blue-600" />
                    <span>3. Right to Due Legal Process</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    Civil recovery actions require formal, signed notices and judicial oversight. Direct asset seizures without court orders are strictly illegal.
                  </p>
                </div>

                <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-2xs space-y-1.5">
                  <div className="flex items-center gap-2 text-slate-900 font-bold text-sm">
                    <Landmark className="w-4 h-4 text-purple-600" />
                    <span>4. Right to Lok Adalat Settlement</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    Section 19 of the Legal Services Authorities Act entitles borrowers to resolve debt disputes through Lok Adalat compromise proceedings.
                  </p>
                </div>
              </div>
            </section>

            {/* SECTION 8: 3-TIER ESCALATION MATRIX */}
            <section id="three-tier-escalation-matrix" className="scroll-target space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <TrendingUp className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  7. 3-Tier Escalation Framework Against Abusive Collection
                </h2>
              </div>

              <div className="space-y-3 text-xs sm:text-sm">
                <div className="p-4 rounded-2xl bg-white border border-slate-200/80 shadow-2xs space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-slate-900 text-sm">Level 1: Principal Nodal Officer (PNO) Grievance</span>
                    <span className="px-2 py-0.5 rounded-md bg-blue-100 text-[#1886ff] font-bold text-xs">7 to 10 Days</span>
                  </div>
                  <p className="text-slate-600 leading-relaxed">
                    We submit a formal legal grievance to the bank Principal Nodal Officer with digital evidence of forged notices, demanding termination of the offending recovery agency.
                  </p>
                </div>

                <div className="p-4 rounded-2xl bg-white border border-slate-200/80 shadow-2xs space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-slate-900 text-sm">Level 2: RBI Integrated Ombudsman Escalation</span>
                    <span className="px-2 py-0.5 rounded-md bg-emerald-100 text-emerald-700 font-bold text-xs">15 to 30 Days</span>
                  </div>
                  <p className="text-slate-600 leading-relaxed">
                    If unresolved within 30 days, we escalate the matter to the RBI CMS portal (cms.rbi.org.in) under the Integrated Ombudsman Scheme, seeking regulatory sanctions.
                  </p>
                </div>

                <div className="p-4 rounded-2xl bg-white border border-slate-200/80 shadow-2xs space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="font-bold text-slate-900 text-sm">Level 3: Cyber Police FIR &amp; Bar Council Action</span>
                    <span className="px-2 py-0.5 rounded-md bg-purple-100 text-purple-700 font-bold text-xs">Criminal Stage</span>
                  </div>
                  <p className="text-slate-600 leading-relaxed">
                    For forged seals or severe threats, we register an FIR under Section 66D IT Act and Section 336/340 BNS at the Cyber Crime Police Station and notify the State Bar Council.
                  </p>
                </div>
              </div>
            </section>

            {/* SECTION 9: CHRONOLOGICAL DISPUTE TIMELINE */}
            <section id="chronological-dispute-timeline" className="scroll-target space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <Clock className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  8. Chronological Timeline: From WhatsApp Notice to Full Closure
                </h2>
              </div>

              <div className="border border-slate-200/80 rounded-2xl overflow-x-auto shadow-xs bg-white">
                <table className="w-full text-left text-xs sm:text-sm divide-y divide-slate-200/80">
                  <thead className="bg-slate-50 text-slate-800 font-bold">
                    <tr className="divide-x divide-slate-200/80">
                      <th className="px-3.5 py-3 font-extrabold text-[#0C2756]">Timeline</th>
                      <th className="px-3.5 py-3">Procedural Phase</th>
                      <th className="px-3.5 py-3">Rogue Collection Action</th>
                      <th className="px-3.5 py-3">CredSettle Defense Strategy</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-200/80 text-slate-700 font-normal">
                    <tr className="divide-x divide-slate-200/80 hover:bg-slate-50/60">
                      <td className="px-3.5 py-2.5 font-bold text-slate-900">Day 1 to 3</td>
                      <td className="px-3.5 py-2.5">Notice Receipt</td>
                      <td className="px-3.5 py-2.5">Fake notice demanding immediate payment</td>
                      <td className="px-3.5 py-2.5">Forensic audit &amp; Bar Council verification</td>
                    </tr>
                    <tr className="divide-x divide-slate-200/80 hover:bg-slate-50/60">
                      <td className="px-3.5 py-2.5 font-bold text-slate-900">Day 4 to 7</td>
                      <td className="px-3.5 py-2.5">Legal Reply</td>
                      <td className="px-3.5 py-2.5">Automated calls &amp; repeated threat messages</td>
                      <td className="px-3.5 py-2.5">Serve cease-and-desist notice to bank</td>
                    </tr>
                    <tr className="divide-x divide-slate-200/80 bg-blue-50/30 hover:bg-blue-50/50">
                      <td className="px-3.5 py-2.5 font-bold text-[#1886ff]">Day 8 to 21</td>
                      <td className="px-3.5 py-2.5">Regulatory Action</td>
                      <td className="px-3.5 py-2.5">Harassment ceases following formal notice</td>
                      <td className="px-3.5 py-2.5 font-semibold text-blue-900">File Cyber Crime &amp; RBI Ombudsman petitions</td>
                    </tr>
                    <tr className="divide-x divide-slate-200/80 hover:bg-slate-50/60">
                      <td className="px-3.5 py-2.5 font-bold text-emerald-800">Day 22 to 60</td>
                      <td className="px-3.5 py-2.5">OTS Settlement</td>
                      <td className="px-3.5 py-2.5">Bank Credit Committee assumes direct control</td>
                      <td className="px-3.5 py-2.5 font-semibold text-emerald-800">Secure 40% to 60% OTS waiver and final NDC</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </section>

            {/* SECTION 10: SPECIALIZED REAL-WORLD SCENARIOS */}
            <section id="specialized-fraud-scenarios" className="scroll-target space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <Briefcase className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  9. Specialized Real-World Scenarios: 7-Day Loan Apps &amp; Arbitrations
                </h2>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3.5">
                <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-2xs space-y-1.5">
                  <div className="flex items-center gap-2 text-slate-900 font-bold text-sm">
                    <MessageSquareWarning className="w-4 h-4 text-rose-600" />
                    <span>7-Day Instant Loan App Harassment</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    Illegal loan apps send fake police warrants and threat messages. CredSettle files emergency cyber complaints, freezes fraudulent accounts, and halts contact harassment.
                  </p>
                </div>

                <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-2xs space-y-1.5">
                  <div className="flex items-center gap-2 text-slate-900 font-bold text-sm">
                    <Building2 className="w-4 h-4 text-[#1886ff]" />
                    <span>Forged Lok Adalat Summons</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    Collection agencies forge DLSA notices with fake barcodes. We verify docket records with NALSA authorities and initiate regulatory sanctions.
                  </p>
                </div>

                <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-2xs space-y-1.5">
                  <div className="flex items-center gap-2 text-slate-900 font-bold text-sm">
                    <UserCheck className="w-4 h-4 text-purple-600" />
                    <span>Threats of Home &amp; Workplace Raids</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    Agents send fake GPS pins claiming a seizure team is arriving. We issue legal warnings under the penal code, halting trespassing immediately.
                  </p>
                </div>

                <div className="bg-white p-4 rounded-2xl border border-slate-200/80 shadow-2xs space-y-1.5">
                  <div className="flex items-center gap-2 text-slate-900 font-bold text-sm">
                    <Landmark className="w-4 h-4 text-amber-600" />
                    <span>Fabricated Unilateral Arbitrations</span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    Lenders appoint unilateral arbitrators violating Supreme Court rulings in Perkins and TRF Ltd. We challenge jurisdiction, nullifying tainted proceedings.
                  </p>
                </div>
              </div>
            </section>

            {/* SECTION 11: COMPANY PROFILE */}
            <div id="company-profile" className="scroll-target">
              <CompanySection />
            </div>

            {/* SECTION 12: 10 SYNCHRONIZED FAQS */}
            <section id="frequently-asked-questions" className="scroll-target space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <HelpCircle className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  Frequently Asked Questions: WhatsApp Legal Notices
                </h2>
              </div>

              <div className="space-y-3">
                {faqs.map((faq, idx) => {
                  const isOpen = openFaq === idx;
                  return (
                    <div
                      key={idx}
                      className="border border-slate-200/90 rounded-2xl overflow-hidden bg-white shadow-2xs transition-all"
                    >
                      <button
                        onClick={() => toggleFaq(idx)}
                        className="w-full p-4 sm:p-5 text-left font-bold text-slate-900 flex items-center justify-between gap-3 hover:bg-slate-50 transition-colors text-xs sm:text-sm"
                      >
                        <span className="leading-snug">{faq.q}</span>
                        <ChevronDown
                          className={`w-4 h-4 text-[#1886ff] flex-shrink-0 transition-transform duration-200 ${
                            isOpen ? 'rotate-180' : ''
                          }`}
                        />
                      </button>
                      {isOpen && (
                        <div className="px-4 pb-4 sm:px-5 sm:pb-5 text-xs sm:text-sm text-slate-600 leading-relaxed border-t border-slate-100 pt-3 bg-slate-50/50">
                          <p>{faq.a}</p>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </section>

            {/* SECTION 13: CITATIONS & OUTBOUND AUTHORITY GRID */}
            <section id="regulatory-sources" className="scroll-target space-y-4">
              <div className="flex items-center gap-2 pb-2 border-b border-slate-200">
                <Bookmark className="w-5 h-5 text-[#1886ff]" />
                <h2 className="text-lg sm:text-xl md:text-2xl font-bold text-slate-900">
                  Statutory Citations &amp; Outbound Authorities
                </h2>
              </div>

              <div className="p-4 rounded-2xl bg-white border border-slate-200/80 shadow-2xs space-y-2.5 text-xs sm:text-sm text-slate-700">
                <p className="font-semibold text-slate-900">Key Governing Statutes &amp; Precedents:</p>
                <ul className="list-disc pl-5 space-y-1 text-slate-600 text-xs">
                  <li><strong>Section 66D, Information Technology Act, 2000:</strong> Penalties for cheating by personation using communication devices.</li>
                  <li><strong>Section 336 &amp; 340, Bharatiya Nyaya Sanhita, 2023:</strong> Criminal provisions for forgery of official and judicial seals.</li>
                  <li><strong>Section 29 &amp; 30, Advocates Act, 1961:</strong> Exclusive right of enrolled advocates to practice law in India.</li>
                  <li><strong>RBI Fair Practices Code (2022):</strong> Prohibition of coercive recovery tactics and deceptive communications.</li>
                  <li><strong>Re: Cognizance for Extension of Limitation (2020) SCC Online SC 529:</strong> Legal principles governing digital service of notices.</li>
                  <li><strong>Section 21, CICRA 2005:</strong> Mandatory rectification of wrongful credit bureau submissions.</li>
                </ul>
              </div>

              <div className="space-y-2">
                <p className="text-xs font-bold uppercase tracking-wider text-slate-600">Official Portals:</p>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 text-xs">
                  <a
                    href="https://www.rbi.org.in"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="p-2.5 rounded-xl border border-slate-200 bg-white hover:border-[#1886ff] hover:text-[#1886ff] transition-all flex items-center justify-between group shadow-2xs"
                  >
                    <span className="font-semibold truncate">Reserve Bank of India</span>
                    <ExternalLink className="w-3 h-3 text-slate-400 group-hover:text-[#1886ff]" />
                  </a>
                  <a
                    href="https://services.ecourts.gov.in"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="p-2.5 rounded-xl border border-slate-200 bg-white hover:border-[#1886ff] hover:text-[#1886ff] transition-all flex items-center justify-between group shadow-2xs"
                  >
                    <span className="font-semibold truncate">e-Courts Services Portal</span>
                    <ExternalLink className="w-3 h-3 text-slate-400 group-hover:text-[#1886ff]" />
                  </a>
                  <a
                    href="https://cybercrime.gov.in"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="p-2.5 rounded-xl border border-slate-200 bg-white hover:border-[#1886ff] hover:text-[#1886ff] transition-all flex items-center justify-between group shadow-2xs"
                  >
                    <span className="font-semibold truncate">Cyber Crime Portal</span>
                    <ExternalLink className="w-3 h-3 text-slate-400 group-hover:text-[#1886ff]" />
                  </a>
                  <a
                    href="https://cms.rbi.org.in"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="p-2.5 rounded-xl border border-slate-200 bg-white hover:border-[#1886ff] hover:text-[#1886ff] transition-all flex items-center justify-between group shadow-2xs"
                  >
                    <span className="font-semibold truncate">RBI Integrated Ombudsman</span>
                    <ExternalLink className="w-3 h-3 text-slate-400 group-hover:text-[#1886ff]" />
                  </a>
                  <a
                    href="https://www.indiacode.nic.in"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="p-2.5 rounded-xl border border-slate-200 bg-white hover:border-[#1886ff] hover:text-[#1886ff] transition-all flex items-center justify-between group shadow-2xs"
                  >
                    <span className="font-semibold truncate">India Code Portal</span>
                    <ExternalLink className="w-3 h-3 text-slate-400 group-hover:text-[#1886ff]" />
                  </a>
                  <a
                    href="https://www.cibil.com"
                    target="_blank"
                    rel="noopener noreferrer"
                    className="p-2.5 rounded-xl border border-slate-200 bg-white hover:border-[#1886ff] hover:text-[#1886ff] transition-all flex items-center justify-between group shadow-2xs"
                  >
                    <span className="font-semibold truncate">TransUnion CIBIL</span>
                    <ExternalLink className="w-3 h-3 text-slate-400 group-hover:text-[#1886ff]" />
                  </a>
                </div>
              </div>

              <div className="space-y-2 pt-2">
                <p className="text-xs font-bold uppercase tracking-wider text-slate-600">Related Legal Guides on CredSettle:</p>
                <div className="flex flex-wrap gap-1.5">
                  {[
                    { title: 'Stop Recovery Harassment', href: '/how-to-stop-recovery-agent-harassment' },
                    { title: 'Section 138 Cheque Bounce', href: '/cheque-bounce-case-defense-section-138' },
                    { title: 'Bailable Warrant Defense', href: '/bailable-warrant-for-loan-default' },
                    { title: '7-Day Loan App Defense', href: '/7-day-loan-app-harassment-morphed-photos' },
                    { title: 'Can You Go to Jail for Debt', href: '/can-i-go-to-jail-for-loan-default-in-india' },
                    { title: 'Personal Loan Settlement', href: '/personal-loan-settlement' },
                    { title: 'Lok Adalat Loan Settlement', href: '/lok-adalat-personal-loan-settlement' },
                    { title: 'Arbitration Notice Defense', href: '/arbitration-notice-personal-loan-default' },
                    { title: 'Convert Settled to Closed', href: '/convert-settled-status-to-closed' },
                    { title: 'Credit Card Settlement', href: '/credit-card-settlement' }
                  ].map((guide, idx) => (
                    <Link
                      key={idx}
                      href={guide.href}
                      className="px-2.5 py-1 rounded-lg bg-slate-100 hover:bg-blue-50 text-slate-700 hover:text-[#1886ff] text-xs font-medium border border-slate-200/80 transition-all"
                    >
                      {guide.title}
                    </Link>
                  ))}
                </div>
              </div>
            </section>
          </article>

          {/* ================= RIGHT COLUMN: STICKY SIDEBAR ================= */}
          <aside className="space-y-5 sticky top-6">
            
            {/* AUTHOR BIO CARD */}
            <div className="bg-white rounded-2xl border border-slate-200/80 shadow-xs p-4 sm:p-5 space-y-3 text-slate-800">
              <div className="flex items-center gap-3">
                <div className="w-12 h-12 rounded-full bg-gradient-to-tr from-blue-600 to-[#1886ff] text-white font-extrabold flex items-center justify-center text-base border-2 border-blue-200 flex-shrink-0 shadow-2xs">
                  AJ
                </div>
                <div>
                  <h3 className="font-bold text-slate-900 text-sm">Ashish Jhangra</h3>
                  <p className="text-[11px] font-semibold text-[#1886ff]">
                    Legal &amp; Debt Resolution Professional
                  </p>
                  <p className="text-[10px] text-slate-500">CredSettle Research Head</p>
                </div>
              </div>
              <p className="text-xs text-slate-600 leading-relaxed border-t border-slate-100 pt-2.5">
                Specialist in Indian consumer banking law, debt dispute defense, and regulatory protection against unauthorized debt collection under RBI frameworks.
              </p>
            </div>

            {/* EMERGENCY CTA CARD (#2452ae) */}
            <div
              className="rounded-2xl p-4 sm:p-5 text-white shadow-md space-y-3"
              style={{ backgroundColor: '#2452ae' }}
            >
              <div className="flex items-center gap-2">
                <BadgeAlert className="w-5 h-5 text-amber-300 animate-pulse" />
                <span className="text-xs font-black uppercase tracking-wider text-blue-100">
                  Urgent Notice Defense
                </span>
              </div>
              <h3 className="text-base font-extrabold leading-snug">
                Received a WhatsApp Legal Notice?
              </h3>
              <p className="text-xs text-white/90 leading-relaxed">
                Connect with CredSettle legal experts for instant Bar Council verification, e-Courts case checks, and cease-and-desist protection.
              </p>
              <div className="pt-1 space-y-2">
                <a
                  href="tel:+918800226635"
                  className="w-full py-2.5 px-4 rounded-xl bg-white text-blue-900 font-extrabold text-xs flex items-center justify-center gap-2 hover:bg-slate-50 transition-all shadow-xs"
                >
                  <Phone className="w-3.5 h-3.5 text-[#1886ff]" />
                  <span>Call: +91-8800226635</span>
                </a>
                <Link
                  href="/contact"
                  className="w-full py-2 px-4 rounded-xl bg-blue-600/40 hover:bg-blue-600/60 text-white font-bold text-xs flex items-center justify-center gap-1.5 transition-all border border-white/20"
                >
                  <span>Verify Your Legal Notice Today</span>
                  <ArrowRight className="w-3 h-3" />
                </Link>
              </div>
            </div>

            {/* TRUST BADGES */}
            <div className="bg-white rounded-2xl border border-slate-200/80 shadow-xs p-4 space-y-2.5 text-xs text-slate-700">
              <div className="flex items-center gap-2 text-slate-900 font-bold pb-1.5 border-b border-slate-100">
                <ShieldCheck className="w-4 h-4 text-emerald-600" />
                <span>CredSettle Protection Standards</span>
              </div>
              <div className="flex items-center gap-2">
                <Check className="w-3.5 h-3.5 text-emerald-600 flex-shrink-0" />
                <span>100% Confidential Consultations</span>
              </div>
              <div className="flex items-center gap-2">
                <Check className="w-3.5 h-3.5 text-emerald-600 flex-shrink-0" />
                <span>Pan-India Court Network</span>
              </div>
              <div className="flex items-center gap-2">
                <Check className="w-3.5 h-3.5 text-emerald-600 flex-shrink-0" />
                <span>RBI Fair Practices Enforcement</span>
              </div>
              <div className="flex items-center gap-2">
                <Check className="w-3.5 h-3.5 text-emerald-600 flex-shrink-0" />
                <span>Unconditional No Dues Guarantee</span>
              </div>
            </div>

          </aside>
        </div>
      </div>
    </main>
  );
}
