// Auto-generated location data for loan settlement by city pages
// Total locations: 1517

export interface LocationData {
  slug: string;
  name: string;
  title: string;
  description: string;
}

export function getCityMetaTitle(name: string): string {
  const full = `Loan Settlement in ${name} | CredSettle`;
  if (full.length <= 60) return full;

  const compact = `Loan Settlement ${name} | CredSettle`;
  if (compact.length <= 60) return compact;

  const noBrand = `Loan Settlement in ${name}`;
  if (noBrand.length <= 60) return noBrand;

  return `Loan Settlement - ${name}`.slice(0, 60);
}

export function getCityMetaDescription(name: string): string {
  let desc = `Settle your loans in ${name} legally. Stop recovery harassment & resolve credit card or personal debt with CredSettle. Free consultation.`;
  if (desc.length <= 155 && desc.length >= 130) return desc;

  if (desc.length > 155) {
    desc = `Settle your loans in ${name} legally. Stop recovery harassment and resolve credit card & personal debt with CredSettle.`;
  }

  if (desc.length > 155) {
    desc = `Settle loans in ${name} legally. Stop bank harassment & resolve debt with CredSettle. Free consultation.`;
  }

  if (desc.length > 155) {
    desc = `Legal loan settlement in ${name}. Stop harassment and settle debt with CredSettle.`;
  }

  if (desc.length < 130) {
    desc = `Get expert legal loan settlement in ${name} with CredSettle. Stop recovery harassment and resolve personal & card debts. Free consultation.`;
  }

  return desc;
}

interface RawLocation {
  slug: string;
  name: string;
}

const rawLocations: RawLocation[] = [
  { slug: "tirap", name: "Tirap" },
  { slug: "fazilka", name: "Fazilka" },
  { slug: "khanpur", name: "Khanpur" },
  { slug: "jamnagar", name: "Jamnagar" },
  { slug: "gurugram-sector-4", name: "Gurugram Sector 4" },
  { slug: "karampura", name: "Karampura" },
  { slug: "dasna-village", name: "Dasna Village" },
  { slug: "chandigarh", name: "Chandigarh" },
  { slug: "govindpuram-sector-2", name: "Govindpuram Sector 2" },
  { slug: "goalpara", name: "Goalpara" },
  { slug: "thoubal", name: "Thoubal" },
  { slug: "hamirpur", name: "Hamirpur" },
  { slug: "noida-sector-18", name: "Noida Sector 18" },
  { slug: "hoshiarpur", name: "Hoshiarpur" },
  { slug: "noida-sector-144", name: "Noida Sector 144" },
  { slug: "shastri-nagar-block-b", name: "Shastri Nagar Block B" },
  { slug: "tiruchirappalli", name: "Tiruchirappalli" },
  { slug: "dindori", name: "Dindori" },
  { slug: "gurugram-sector-26", name: "Gurugram Sector 26" },
  { slug: "aiims-metro", name: "AIIMS Metro" },
  { slug: "srinagar", name: "Srinagar" },
  { slug: "kanchipuram", name: "Kanchipuram" },
  { slug: "shastri-nagar-block-d", name: "Shastri Nagar Block D" },
  { slug: "govindpuram-sector-8", name: "Govindpuram Sector 8" },
  { slug: "dhamtari", name: "Dhamtari" },
  { slug: "khargone", name: "Khargone" },
  { slug: "ramgarh", name: "Ramgarh" },
  { slug: "noida-sector-71", name: "Noida Sector 71" },
  { slug: "gurugram-sector-9", name: "Gurugram Sector 9" },
  { slug: "sahibganj", name: "Sahibganj" },
  { slug: "kavi-nagar-sector-10", name: "Kavi Nagar Sector 10" },
  { slug: "noida-sector-31", name: "Noida Sector 31" },
  { slug: "churu", name: "Churu" },
  { slug: "greater-noida-sector-beta-2", name: "Greater Noida Sector Beta 2" },
  { slug: "vaishali-sector-4", name: "Vaishali Sector 4" },
  { slug: "dasna-industrial-area", name: "Dasna Industrial Area" },
  { slug: "mandi", name: "Mandi" },
  { slug: "faridabad-sector-31", name: "Faridabad Sector 31" },
  { slug: "noida-sector-149", name: "Noida Sector 149" },
  { slug: "upper-subansiri", name: "Upper Subansiri" },
  { slug: "gurugram-sector-22a", name: "Gurugram Sector 22A" },
  { slug: "haridwar", name: "Haridwar" },
  { slug: "poonch", name: "Poonch" },
  { slug: "sonbhadra", name: "Sonbhadra" },
  { slug: "birbhum", name: "Birbhum" },
  { slug: "meerut", name: "Meerut" },
  { slug: "noida-sector-134", name: "Noida Sector 134" },
  { slug: "madhya-pradesh", name: "Madhya Pradesh" },
  { slug: "jaipur", name: "Jaipur" },
  { slug: "khajuri-khas", name: "Khajuri Khas" },
  { slug: "dhanbad", name: "Dhanbad" },
  { slug: "jharsuguda", name: "Jharsuguda" },
  { slug: "noida-sector-39", name: "Noida Sector 39" },
  { slug: "noida-sector-155", name: "Noida Sector 155" },
  { slug: "mizoram", name: "Mizoram" },
  { slug: "gurgaon", name: "Gurgaon" },
  { slug: "varanasi", name: "Varanasi" },
  { slug: "jehanabad", name: "Jehanabad" },
  { slug: "sector-zeta-4", name: "Sector Zeta 4" },
  { slug: "rewari", name: "Rewari" },
  { slug: "patan", name: "Patan" },
  { slug: "jodhpur", name: "Jodhpur" },
  { slug: "rohini-sector-24", name: "Rohini Sector 24" },
  { slug: "dwarka-mor", name: "Dwarka Mor" },
  { slug: "noida-sector-12", name: "Noida Sector 12" },
  { slug: "gaya", name: "Gaya" },
  { slug: "vijayapura", name: "Vijayapura" },
  { slug: "noida-sector-60", name: "Noida Sector 60" },
  { slug: "sidhi", name: "Sidhi" },
  { slug: "sant-ravidas-nagar", name: "Sant Ravidas Nagar" },
  { slug: "leh", name: "Leh" },
  { slug: "mumbai-city", name: "Mumbai City" },
  { slug: "adarsh-nagar", name: "Adarsh Nagar" },
  { slug: "punjabi-bagh-west", name: "Punjabi Bagh West" },
  { slug: "faridabad-sector-35", name: "Faridabad Sector 35" },
  { slug: "shahdara-depot", name: "Shahdara Depot" },
  { slug: "dumka", name: "Dumka" },
  { slug: "bhadradri-kothagudem", name: "Bhadradri Kothagudem" },
  { slug: "imphal", name: "Imphal" },
  { slug: "noida-sector-114", name: "Noida Sector 114" },
  { slug: "hindon-air-force-station", name: "Hindon Air Force Station" },
  { slug: "wave-executive-floors", name: "Wave Executive Floors" },
  { slug: "wave-city-sector-8", name: "Wave City Sector 8" },
  { slug: "jatwara", name: "Jatwara" },
  { slug: "mackay", name: "Mackay" },
  { slug: "mathura", name: "Mathura" },
  { slug: "koraput", name: "Koraput" },
  { slug: "faridabad-sector-17", name: "Faridabad Sector 17" },
  { slug: "muradnagar-industrial-area", name: "Muradnagar Industrial Area" },
  { slug: "surajpur", name: "Surajpur" },
  { slug: "junagadh", name: "Junagadh" },
  { slug: "nehru-place", name: "Nehru Place" },
  { slug: "punjabi-bagh-metro", name: "Punjabi Bagh Metro" },
  { slug: "pandav-nagar", name: "Pandav Nagar" },
  { slug: "noida-sector-100", name: "Noida Sector 100" },
  { slug: "noida-sector-28", name: "Noida Sector 28" },
  { slug: "shaheen-bagh", name: "Shaheen Bagh" },
  { slug: "belagavi", name: "Belagavi" },
  { slug: "narela", name: "Narela" },
  { slug: "udaipur", name: "Udaipur" },
  { slug: "crossing-republik-ajnara-gen-x", name: "Crossing Republik Ajnara Gen X" },
  { slug: "railway-colony", name: "Railway Colony" },
  { slug: "una", name: "Una" },
  { slug: "gyan-khand-1", name: "Gyan Khand 1" },
  { slug: "karampura-industrial-area", name: "Karampura Industrial Area" },
  { slug: "faridabad-sector-15", name: "Faridabad Sector 15" },
  { slug: "raigad", name: "Raigad" },
  { slug: "sector-xu-2", name: "Sector Xu 2" },
  { slug: "vaibhav-khand", name: "Vaibhav Khand" },
  { slug: "crossings-republic-gaur-global-village", name: "Crossings Republic Gaur Global Village" },
  { slug: "nalgonda", name: "Nalgonda" },
  { slug: "bhavnagar", name: "Bhavnagar" },
  { slug: "noida-sector-21", name: "Noida Sector 21" },
  { slug: "purulia", name: "Purulia" },
  { slug: "karaikal", name: "Karaikal" },
  { slug: "noida-sector-65", name: "Noida Sector 65" },
  { slug: "greater-noida-sector-omicron-2", name: "Greater Noida Sector Omicron 2" },
  { slug: "doda", name: "Doda" },
  { slug: "tronica-city-sector-d", name: "Tronica City Sector D" },
  { slug: "panipat", name: "Panipat" },
  { slug: "gondia", name: "Gondia" },
  { slug: "mahbubabad", name: "Mahbubabad" },
  { slug: "vasundhara-sector-1", name: "Vasundhara Sector 1" },
  { slug: "gurugram-sector-35", name: "Gurugram Sector 35" },
  { slug: "gurugram-sector-31", name: "Gurugram Sector 31" },
  { slug: "indraprastha-park", name: "Indraprastha Park" },
  { slug: "noida-sector-37", name: "Noida Sector 37" },
  { slug: "greater-noida-sector-delta-4", name: "Greater Noida Sector Delta 4" },
  { slug: "vasant-kunj-bus-stand", name: "Vasant Kunj Bus Stand" },
  { slug: "siddharth-vihar-sector-4", name: "Siddharth Vihar Sector 4" },
  { slug: "nadia", name: "Nadia" },
  { slug: "purba-medinipur", name: "Purba Medinipur" },
  { slug: "indore", name: "Indore" },
  { slug: "gurugram-sector-37c", name: "Gurugram Sector 37C" },
  { slug: "noida-sector-6", name: "Noida Sector 6" },
  { slug: "jalandhar", name: "Jalandhar" },
  { slug: "niti-bagh-colony", name: "Niti Bagh Colony" },
  { slug: "east-khasi-hills", name: "East Khasi Hills" },
  { slug: "panchkula", name: "Panchkula" },
  { slug: "srikakulam", name: "Srikakulam" },
  { slug: "hooghly", name: "Hooghly" },
  { slug: "seraikela-kharsawan", name: "Seraikela-Kharsawan" },
  { slug: "yamuna-expressway-sector-24", name: "Yamuna Expressway Sector 24" },
  { slug: "bhopal", name: "Bhopal" },
  { slug: "upper-siang", name: "Upper Siang" },
  { slug: "washim", name: "Washim" },
  { slug: "rajdhani-park", name: "Rajdhani Park" },
  { slug: "sector-chi-3", name: "Sector Chi 3" },
  { slug: "kolkata", name: "Kolkata" },
  { slug: "west-champaran", name: "West Champaran" },
  { slug: "andaman-and-nicobar-islands", name: "Andaman and Nicobar Islands" },
  { slug: "noida-sector-42", name: "Noida Sector 42" },
  { slug: "seemapuri", name: "Seemapuri" },
  { slug: "paharganj", name: "Paharganj" },
  { slug: "udham-singh-nagar", name: "Udham Singh Nagar" },
  { slug: "nalbari", name: "Nalbari" },
  { slug: "gurugram-sector-10a", name: "Gurugram Sector 10A" },
  { slug: "ecotech-5", name: "Ecotech 5" },
  { slug: "shakarpur", name: "Shakarpur" },
  { slug: "gurugram-sector-22", name: "Gurugram Sector 22" },
  { slug: "barakhamba-road", name: "Barakhamba Road" },
  { slug: "gurugram-sector-33", name: "Gurugram Sector 33" },
  { slug: "latehar", name: "Latehar" },
  { slug: "whyalla", name: "Whyalla" },
  { slug: "lal-kuan", name: "Lal Kuan" },
  { slug: "vaishali-sector-3", name: "Vaishali Sector 3" },
  { slug: "hauz-khas", name: "Hauz Khas" },
  { slug: "knowledge-park-2", name: "Knowledge Park 2" },
  { slug: "betul", name: "Betul" },
  { slug: "dehradun", name: "Dehradun" },
  { slug: "badarpur", name: "Badarpur" },
  { slug: "dadra-and-nagar-haveli-and-daman-and-diu", name: "Dadra and Nagar Haveli and Daman and Diu" },
  { slug: "patiala", name: "Patiala" },
  { slug: "palam", name: "Palam" },
  { slug: "pune", name: "Pune" },
  { slug: "kurnool", name: "Kurnool" },
  { slug: "lajpat-nagar-metro", name: "Lajpat Nagar Metro" },
  { slug: "south-24-parganas", name: "South 24 Parganas" },
  { slug: "noida-sector-87", name: "Noida Sector 87" },
  { slug: "wokha", name: "Wokha" },
  { slug: "uttarkashi", name: "Uttarkashi" },
  { slug: "crossings-republic-supertech", name: "Crossings Republic Supertech" },
  { slug: "shimla", name: "Shimla" },
  { slug: "sangrur", name: "Sangrur" },
  { slug: "purba-bardhaman", name: "Purba Bardhaman" },
  { slug: "nirman-vihar-metro", name: "Nirman Vihar Metro" },
  { slug: "bishnupur", name: "Bishnupur" },
  { slug: "gurugram-sector-3", name: "Gurugram Sector 3" },
  { slug: "ganjam", name: "Ganjam" },
  { slug: "sabzi-mandi", name: "Sabzi Mandi" },
  { slug: "gurugram-sector-29", name: "Gurugram Sector 29" },
  { slug: "vaishali-extension", name: "Vaishali Extension" },
  { slug: "west-siang", name: "West Siang" },
  { slug: "gurugram-sector-15-part-2", name: "Gurugram Sector 15 Part 2" },
  { slug: "nagaur", name: "Nagaur" },
  { slug: "jangaon", name: "Jangaon" },
  { slug: "siddharthnagar", name: "Siddharthnagar" },
  { slug: "jammu", name: "Jammu" },
  { slug: "new-delhi-railway-station", name: "New Delhi Railway Station" },
  { slug: "dhalai", name: "Dhalai" },
  { slug: "tirupattur", name: "Tirupattur" },
  { slug: "noida-sector-96", name: "Noida Sector 96" },
  { slug: "manesar", name: "Manesar" },
  { slug: "bijnor", name: "Bijnor" },
  { slug: "sehore", name: "Sehore" },
  { slug: "ratlam", name: "Ratlam" },
  { slug: "noida-sector-15a", name: "Noida Sector 15A" },
  { slug: "lawngtlai", name: "Lawngtlai" },
  { slug: "subhash-nagar", name: "Subhash Nagar" },
  { slug: "noida-sector-25a", name: "Noida Sector 25A" },
  { slug: "surat", name: "Surat" },
  { slug: "knowledge-park-1", name: "Knowledge Park 1" },
  { slug: "kolhapur", name: "Kolhapur" },
  { slug: "bemetara", name: "Bemetara" },
  { slug: "pathanamthitta", name: "Pathanamthitta" },
  { slug: "gurugram-sector-39", name: "Gurugram Sector 39" },
  { slug: "noida-sector-54", name: "Noida Sector 54" },
  { slug: "madurai", name: "Madurai" },
  { slug: "nangloi-metro", name: "Nangloi Metro" },
  { slug: "vaishali-sector-9", name: "Vaishali Sector 9" },
  { slug: "sector-mu-2", name: "Sector Mu 2" },
  { slug: "green-park", name: "Green Park" },
  { slug: "nainital", name: "Nainital" },
  { slug: "noida-sector-137", name: "Noida Sector 137" },
  { slug: "laxmi-nagar", name: "Laxmi Nagar" },
  { slug: "gtb-nagar", name: "GTB Nagar" },
  { slug: "niti-khand-1", name: "Niti Khand 1" },
  { slug: "noida-sector-97", name: "Noida Sector 97" },
  { slug: "gandhinagar", name: "Gandhinagar" },
  { slug: "kabirdham", name: "Kabirdham" },
  { slug: "shivpuri", name: "Shivpuri" },
  { slug: "vasant-vihar", name: "Vasant Vihar" },
  { slug: "ip-extension", name: "IP Extension" },
  { slug: "gurugram-sector-23a", name: "Gurugram Sector 23A" },
  { slug: "noida-sector-116", name: "Noida Sector 116" },
  { slug: "saket-metro", name: "Saket Metro" },
  { slug: "south-extension", name: "South Extension" },
  { slug: "muradnagar", name: "Muradnagar" },
  { slug: "pari-chowk", name: "Pari Chowk" },
  { slug: "crossing-republic", name: "Crossing Republic" },
  { slug: "pratap-vihar", name: "Pratap Vihar" },
  { slug: "noida-sector-99", name: "Noida Sector 99" },
  { slug: "govindpuram-sector-1", name: "Govindpuram Sector 1" },
  { slug: "chandauli", name: "Chandauli" },
  { slug: "west-garo-hills", name: "West Garo Hills" },
  { slug: "mayur-vihar-phase-ii", name: "Mayur Vihar Phase II" },
  { slug: "noida-sector-19", name: "Noida Sector 19" },
  { slug: "faridabad-sector-34", name: "Faridabad Sector 34" },
  { slug: "dwarka-sector-14", name: "Dwarka Sector 14" },
  { slug: "puducherry", name: "Puducherry" },
  { slug: "chhattisgarh", name: "Chhattisgarh" },
  { slug: "welcome-colony", name: "Welcome Colony" },
  { slug: "faridabad-sector-21", name: "Faridabad Sector 21" },
  { slug: "noida-sector-26", name: "Noida Sector 26" },
  { slug: "saket", name: "Saket" },
  { slug: "sector-rho-2", name: "Sector Rho 2" },
  { slug: "medak", name: "Medak" },
  { slug: "noida-sector-17", name: "Noida Sector 17" },
  { slug: "faridabad-sector-3", name: "Faridabad Sector 3" },
  { slug: "okhla-vihar", name: "Okhla Vihar" },
  { slug: "moti-bagh", name: "Moti Bagh" },
  { slug: "noida-extension-sector-3", name: "Noida Extension Sector 3" },
  { slug: "tikri-border", name: "Tikri Border" },
  { slug: "noida-sector-131", name: "Noida Sector 131" },
  { slug: "north-goa", name: "North Goa" },
  { slug: "bhopura-extension", name: "Bhopura Extension" },
  { slug: "noida-sector-92", name: "Noida Sector 92" },
  { slug: "noida-sector-55", name: "Noida Sector 55" },
  { slug: "godda", name: "Godda" },
  { slug: "amrapali-leisure-valley", name: "Amrapali Leisure Valley" },
  { slug: "bhilai", name: "Bhilai" },
  { slug: "chamarajanagara", name: "Chamarajanagara" },
  { slug: "raigarh", name: "Raigarh" },
  { slug: "saharsa", name: "Saharsa" },
  { slug: "gurugram-sector-27", name: "Gurugram Sector 27" },
  { slug: "noida-extension-sector-1", name: "Noida Extension Sector 1" },
  { slug: "telangana", name: "Telangana" },
  { slug: "sector-theta-2", name: "Sector Theta 2" },
  { slug: "karimnagar", name: "Karimnagar" },
  { slug: "noida-sector-121", name: "Noida Sector 121" },
  { slug: "kullu", name: "Kullu" },
  { slug: "sector-rho-1", name: "Sector Rho 1" },
  { slug: "jhalawar", name: "Jhalawar" },
  { slug: "bhubaneswar", name: "Bhubaneswar" },
  { slug: "noida-sector-35", name: "Noida Sector 35" },
  { slug: "noida-sector-103", name: "Noida Sector 103" },
  { slug: "noida-sector-115", name: "Noida Sector 115" },
  { slug: "noida-sector-83", name: "Noida Sector 83" },
  { slug: "mamit", name: "Mamit" },
  { slug: "ecotech-4", name: "Ecotech 4" },
  { slug: "mayur-vihar-phase-i", name: "Mayur Vihar Phase I" },
  { slug: "satna", name: "Satna" },
  { slug: "hisar", name: "Hisar" },
  { slug: "noida", name: "Noida" },
  { slug: "noida-sector-143", name: "Noida Sector 143" },
  { slug: "tikri-kalan", name: "Tikri Kalan" },
  { slug: "kirti-nagar", name: "Kirti Nagar" },
  { slug: "gurugram-sector-32", name: "Gurugram Sector 32" },
  { slug: "porbandar", name: "Porbandar" },
  { slug: "kargil", name: "Kargil" },
  { slug: "changlang", name: "Changlang" },
  { slug: "raj-nagar-sector-4", name: "Raj Nagar Sector 4" },
  { slug: "khetlal", name: "Khetlal" },
  { slug: "noida-sector-145", name: "Noida Sector 145" },
  { slug: "bijwasan", name: "Bijwasan" },
  { slug: "east-jaintia-hills", name: "East Jaintia Hills" },
  { slug: "qutub-minar", name: "Qutub Minar" },
  { slug: "faridabad-sector-12", name: "Faridabad Sector 12" },
  { slug: "lunglei", name: "Lunglei" },
  { slug: "farrukhabad", name: "Farrukhabad" },
  { slug: "mansa", name: "Mansa" },
  { slug: "janakpuri-west-metro", name: "Janakpuri West Metro" },
  { slug: "baran", name: "Baran" },
  { slug: "ito-metro", name: "ITO Metro" },
  { slug: "subhash-nagar-metro", name: "Subhash Nagar Metro" },
  { slug: "dindigul", name: "Dindigul" },
  { slug: "nh-9-ghaziabad", name: "NH-9 Ghaziabad" },
  { slug: "dasna-jail-area", name: "Dasna Jail Area" },
  { slug: "patna", name: "Patna" },
  { slug: "mehrauli", name: "Mehrauli" },
  { slug: "yamuna-expressway-sector-18", name: "Yamuna Expressway Sector 18" },
  { slug: "bhind", name: "Bhind" },
  { slug: "bhilwara", name: "Bhilwara" },
  { slug: "lucknow", name: "Lucknow" },
  { slug: "noida-sector-143b", name: "Noida Sector 143B" },
  { slug: "ernakulam", name: "Ernakulam" },
  { slug: "noida-sector-112", name: "Noida Sector 112" },
  { slug: "lohit", name: "Lohit" },
  { slug: "etawah", name: "Etawah" },
  { slug: "valsad", name: "Valsad" },
  { slug: "govindpuram-sector-6", name: "Govindpuram Sector 6" },
  { slug: "mumbai-suburban", name: "Mumbai Suburban" },
  { slug: "loni-border", name: "Loni Border" },
  { slug: "govindpuram-sector-9", name: "Govindpuram Sector 9" },
  { slug: "bandipora", name: "Bandipora" },
  { slug: "faridabad-sector-30", name: "Faridabad Sector 30" },
  { slug: "itanagar", name: "Itanagar" },
  { slug: "coimbatore", name: "Coimbatore" },
  { slug: "sagar", name: "Sagar" },
  { slug: "shastri-nagar-block-c", name: "Shastri Nagar Block C" },
  { slug: "noida-sector-157", name: "Noida Sector 157" },
  { slug: "faridabad-sector-25", name: "Faridabad Sector 25" },
  { slug: "mokokchung", name: "Mokokchung" },
  { slug: "noida-sector-44", name: "Noida Sector 44" },
  { slug: "najafgarh-metro", name: "Najafgarh Metro" },
  { slug: "surya-nagar", name: "Surya Nagar" },
  { slug: "noida-sector-89", name: "Noida Sector 89" },
  { slug: "balrampur", name: "Balrampur" },
  { slug: "dharamshala", name: "Dharamshala" },
  { slug: "solapur", name: "Solapur" },
  { slug: "wave-city-sector-2", name: "Wave City Sector 2" },
  { slug: "dilshad-garden", name: "Dilshad Garden" },
  { slug: "chandrapur", name: "Chandrapur" },
  { slug: "noida-sector-9", name: "Noida Sector 9" },
  { slug: "lakhimpur", name: "Lakhimpur" },
  { slug: "vasundhara-sector-10", name: "Vasundhara Sector 10" },
  { slug: "sahibabad", name: "Sahibabad" },
  { slug: "nandurbar", name: "Nandurbar" },
  { slug: "gurugram-sector-1", name: "Gurugram Sector 1" },
  { slug: "sanjay-nagar-sector-4", name: "Sanjay Nagar Sector 4" },
  { slug: "gurugram-sector-28", name: "Gurugram Sector 28" },
  { slug: "malda", name: "Malda" },
  { slug: "rajiv-chowk", name: "Rajiv Chowk" },
  { slug: "diu", name: "Diu" },
  { slug: "noida-sector-93b", name: "Noida Sector 93B" },
  { slug: "satyawati-college", name: "Satyawati College" },
  { slug: "vasundhara-sector-3", name: "Vasundhara Sector 3" },
  { slug: "ratnagiri", name: "Ratnagiri" },
  { slug: "abupur", name: "Abupur" },
  { slug: "mysore", name: "Mysore" },
  { slug: "tumakuru", name: "Tumakuru" },
  { slug: "golaghat", name: "Golaghat" },
  { slug: "sabarkantha", name: "Sabarkantha" },
  { slug: "greater-noida-sector-gamma-2", name: "Greater Noida Sector Gamma 2" },
  { slug: "himachal-pradesh", name: "Himachal Pradesh" },
  { slug: "kokrajhar", name: "Kokrajhar" },
  { slug: "jalore", name: "Jalore" },
  { slug: "lahaul-and-spiti", name: "Lahaul and Spiti" },
  { slug: "niti-khand-2", name: "Niti Khand 2" },
  { slug: "tamil-nadu", name: "Tamil Nadu" },
  { slug: "sant-kabir-nagar", name: "Sant Kabir Nagar" },
  { slug: "sundar-nagar", name: "Sundar Nagar" },
  { slug: "rajkot", name: "Rajkot" },
  { slug: "shamli", name: "Shamli" },
  { slug: "noida-sector-107", name: "Noida Sector 107" },
  { slug: "dibang-valley", name: "Dibang Valley" },
  { slug: "patel-chowk", name: "Patel Chowk" },
  { slug: "yamuna-bank", name: "Yamuna Bank" },
  { slug: "techzone-2", name: "Techzone 2" },
  { slug: "greater-noida-sector-alpha-2", name: "Greater Noida Sector Alpha 2" },
  { slug: "cachar", name: "Cachar" },
  { slug: "dhenkanal", name: "Dhenkanal" },
  { slug: "katni", name: "Katni" },
  { slug: "gaur-city-2", name: "Gaur City 2" },
  { slug: "shalimar-garden-ext-1", name: "Shalimar Garden Ext 1" },
  { slug: "faridabad-bus-stand", name: "Faridabad Bus Stand" },
  { slug: "vivek-vihar", name: "Vivek Vihar" },
  { slug: "gopalganj", name: "Gopalganj" },
  { slug: "south-goa", name: "South Goa" },
  { slug: "subarnapur", name: "Subarnapur" },
  { slug: "gurugram-sector-23", name: "Gurugram Sector 23" },
  { slug: "gurugram-sector-21", name: "Gurugram Sector 21" },
  { slug: "bengaluru-urban", name: "Bengaluru Urban" },
  { slug: "kulgam", name: "Kulgam" },
  { slug: "virudhunagar", name: "Virudhunagar" },
  { slug: "pithoragarh", name: "Pithoragarh" },
  { slug: "anand-vihar-depot", name: "Anand Vihar Depot" },
  { slug: "badarpur-border", name: "Badarpur Border" },
  { slug: "balangir", name: "Balangir" },
  { slug: "mohan-nagar", name: "Mohan Nagar" },
  { slug: "albany", name: "Albany" },
  { slug: "rajgarh", name: "Rajgarh" },
  { slug: "siddharth-vihar", name: "Siddharth Vihar" },
  { slug: "sector-chi-4", name: "Sector Chi 4" },
  { slug: "jalgaon", name: "Jalgaon" },
  { slug: "nalanda", name: "Nalanda" },
  { slug: "kishanganj", name: "Kishanganj" },
  { slug: "assam", name: "Assam" },
  { slug: "kondagaon", name: "Kondagaon" },
  { slug: "purnia", name: "Purnia" },
  { slug: "badarpur-metro", name: "Badarpur Metro" },
  { slug: "noida-sector-151", name: "Noida Sector 151" },
  { slug: "rudraprayag", name: "Rudraprayag" },
  { slug: "unnao", name: "Unnao" },
  { slug: "sector-chi-1", name: "Sector Chi 1" },
  { slug: "barnala", name: "Barnala" },
  { slug: "balkh", name: "Balkh" },
  { slug: "prakasam", name: "Prakasam" },
  { slug: "kanshiram-nagar", name: "Kanshiram Nagar" },
  { slug: "faridabad-sector-21b", name: "Faridabad Sector 21B" },
  { slug: "faridabad-sector-32", name: "Faridabad Sector 32" },
  { slug: "sonipat", name: "Sonipat" },
  { slug: "gurugram-sector-18", name: "Gurugram Sector 18" },
  { slug: "mahagun-modern-city", name: "Mahagun Modern City" },
  { slug: "muzaffarpur", name: "Muzaffarpur" },
  { slug: "guwahati", name: "Guwahati" },
  { slug: "noida-sector-102", name: "Noida Sector 102" },
  { slug: "mewat", name: "Mewat" },
  { slug: "noida-sector-138", name: "Noida Sector 138" },
  { slug: "visakhapatnam", name: "Visakhapatnam" },
  { slug: "noida-sector-16", name: "Noida Sector 16" },
  { slug: "panchmahal", name: "Panchmahal" },
  { slug: "gurugram-sector-36", name: "Gurugram Sector 36" },
  { slug: "noida-sector-22", name: "Noida Sector 22" },
  { slug: "sector-63-indirapuram", name: "Sector 63 Indirapuram" },
  { slug: "ladakh", name: "Ladakh" },
  { slug: "ramanathapuram", name: "Ramanathapuram" },
  { slug: "ukhrul", name: "Ukhrul" },
  { slug: "korba", name: "Korba" },
  { slug: "zunheboto", name: "Zunheboto" },
  { slug: "dima-hasao", name: "Dima Hasao" },
  { slug: "gurugram-sector-13", name: "Gurugram Sector 13" },
  { slug: "west-jaintia-hills", name: "West Jaintia Hills" },
  { slug: "east-kameng", name: "East Kameng" },
  { slug: "rohini-east", name: "Rohini East" },
  { slug: "noida-sector-113", name: "Noida Sector 113" },
  { slug: "faridabad-sector-5", name: "Faridabad Sector 5" },
  { slug: "nayagarh", name: "Nayagarh" },
  { slug: "bhadohi", name: "Bhadohi" },
  { slug: "aditya-world-city", name: "Aditya World City" },
  { slug: "muradabad", name: "Muradabad" },
  { slug: "banswara", name: "Banswara" },
  { slug: "rajsamand", name: "Rajsamand" },
  { slug: "chennai", name: "Chennai" },
  { slug: "noida-sector-40", name: "Noida Sector 40" },
  { slug: "rajasthan", name: "Rajasthan" },
  { slug: "jagatsinghpur", name: "Jagatsinghpur" },
  { slug: "dilshad-garden-metro", name: "Dilshad Garden Metro" },
  { slug: "uttar-pradesh", name: "Uttar Pradesh" },
  { slug: "noida-sector-78", name: "Noida Sector 78" },
  { slug: "dakshin-dinajpur", name: "Dakshin Dinajpur" },
  { slug: "faridabad-sector-8", name: "Faridabad Sector 8" },
  { slug: "yamuna-expressway-sector-22", name: "Yamuna Expressway Sector 22" },
  { slug: "bhandara", name: "Bhandara" },
  { slug: "palwal-haryana", name: "Palwal - Haryana" },
  { slug: "dewas", name: "Dewas" },
  { slug: "tulsi-niketan", name: "Tulsi Niketan" },
  { slug: "noida-sector-127", name: "Noida Sector 127" },
  { slug: "kavi-nagar-sector-14", name: "Kavi Nagar Sector 14" },
  { slug: "dimapur", name: "Dimapur" },
  { slug: "gaur-city-1", name: "Gaur City 1" },
  { slug: "noida-sector-68", name: "Noida Sector 68" },
  { slug: "gonda", name: "Gonda" },
  { slug: "noida-sector-66", name: "Noida Sector 66" },
  { slug: "mungeli", name: "Mungeli" },
  { slug: "mayurbhanj", name: "Mayurbhanj" },
  { slug: "noida-sector-79", name: "Noida Sector 79" },
  { slug: "bundi", name: "Bundi" },
  { slug: "supaul", name: "Supaul" },
  { slug: "bharuch", name: "Bharuch" },
  { slug: "south-delhi", name: "South Delhi" },
  { slug: "tughlakabad-metro", name: "Tughlakabad Metro" },
  { slug: "noida-sector-84", name: "Noida Sector 84" },
  { slug: "damoh", name: "Damoh" },
  { slug: "nagapattinam", name: "Nagapattinam" },
  { slug: "raja-garden", name: "Raja Garden" },
  { slug: "indirapuram-vaibhav-khand", name: "Indirapuram Vaibhav Khand" },
  { slug: "noida-extension-sector-17", name: "Noida Extension Sector 17" },
  { slug: "haryana", name: "Haryana" },
  { slug: "ballia", name: "Ballia" },
  { slug: "nyay-khand-1", name: "Nyay Khand 1" },
  { slug: "noida-sector-61", name: "Noida Sector 61" },
  { slug: "rohini-west", name: "Rohini West" },
  { slug: "jaintia-hills", name: "Jaintia Hills" },
  { slug: "wave-city-dream-homes", name: "Wave City Dream Homes" },
  { slug: "noida-sector-132", name: "Noida Sector 132" },
  { slug: "faridabad-sector-9", name: "Faridabad Sector 9" },
  { slug: "sector-delta-i-extension", name: "Sector Delta I Extension" },
  { slug: "ghazipur", name: "Ghazipur" },
  { slug: "sector-omicron-2a", name: "Sector Omicron 2A" },
  { slug: "mangolpuri", name: "Mangolpuri" },
  { slug: "west-singhbhum", name: "West Singhbhum" },
  { slug: "lakhisarai", name: "Lakhisarai" },
  { slug: "noida-sector-154", name: "Noida Sector 154" },
  { slug: "jhabua", name: "Jhabua" },
  { slug: "vaishali-bus-depot", name: "Vaishali Bus Depot" },
  { slug: "jamui", name: "Jamui" },
  { slug: "gurugram-sector-42", name: "Gurugram Sector 42" },
  { slug: "noida-sector-33", name: "Noida Sector 33" },
  { slug: "satara", name: "Satara" },
  { slug: "nicobar", name: "Nicobar" },
  { slug: "gurugram-sector-30", name: "Gurugram Sector 30" },
  { slug: "sector-chi-2", name: "Sector Chi 2" },
  { slug: "gurugram-sector-16", name: "Gurugram Sector 16" },
  { slug: "surajmal-vihar", name: "Surajmal Vihar" },
  { slug: "noida-sector-58", name: "Noida Sector 58" },
  { slug: "nyay-khand-2", name: "Nyay Khand 2" },
  { slug: "duhai-metro-station", name: "Duhai Metro Station" },
  { slug: "kohima", name: "Kohima" },
  { slug: "abhay-khand-3", name: "Abhay Khand 3" },
  { slug: "noida-sector-8", name: "Noida Sector 8" },
  { slug: "govindpuram-sector-3", name: "Govindpuram Sector 3" },
  { slug: "vellore", name: "Vellore" },
  { slug: "shopian", name: "Shopian" },
  { slug: "geraldton", name: "Geraldton" },
  { slug: "faridabad-sector-11", name: "Faridabad Sector 11" },
  { slug: "ito", name: "ITO" },
  { slug: "inderlok", name: "Inderlok" },
  { slug: "hyderabad", name: "Hyderabad" },
  { slug: "nuapada", name: "Nuapada" },
  { slug: "thiruvananthapuram", name: "Thiruvananthapuram" },
  { slug: "senapati", name: "Senapati" },
  { slug: "burari", name: "Burari" },
  { slug: "noida-sector-122", name: "Noida Sector 122" },
  { slug: "brij-vihar", name: "Brij Vihar" },
  { slug: "tilak-nagar", name: "Tilak Nagar" },
  { slug: "noida-sector-13", name: "Noida Sector 13" },
  { slug: "jajpur", name: "Jajpur" },
  { slug: "kolar", name: "Kolar" },
  { slug: "gurugram-sector-7", name: "Gurugram Sector 7" },
  { slug: "gurugram-sector-37", name: "Gurugram Sector 37" },
  { slug: "alipurduar", name: "Alipurduar" },
  { slug: "banka", name: "Banka" },
  { slug: "delhi-university-north-campus", name: "Delhi University - North Campus" },
  { slug: "shastri-nagar-block-a", name: "Shastri Nagar Block A" },
  { slug: "chhattarpur-temple", name: "Chhattarpur Temple" },
  { slug: "greater-noida-sector-omicron-1", name: "Greater Noida Sector Omicron 1" },
  { slug: "noida-sector-15", name: "Noida Sector 15" },
  { slug: "kutch", name: "Kutch" },
  { slug: "greater-noida-sector-omicron-3", name: "Greater Noida Sector Omicron 3" },
  { slug: "indirapuram-nyay-khand-3", name: "Indirapuram Nyay Khand 3" },
  { slug: "sarita-vihar", name: "Sarita Vihar" },
  { slug: "bagalkote", name: "Bagalkote" },
  { slug: "nehrunagar-sector-3", name: "Nehrunagar Sector 3" },
  { slug: "dungarpur", name: "Dungarpur" },
  { slug: "ram-vihar", name: "Ram Vihar" },
  { slug: "faridabad-sector-27", name: "Faridabad Sector 27" },
  { slug: "gir-somnath", name: "Gir Somnath" },
  { slug: "shimoga", name: "Shimoga" },
  { slug: "jamia-millia-islamia", name: "Jamia Millia Islamia" },
  { slug: "noida-sector-38", name: "Noida Sector 38" },
  { slug: "karur", name: "Karur" },
  { slug: "champhai", name: "Champhai" },
  { slug: "kavi-nagar-sector-13", name: "Kavi Nagar Sector 13" },
  { slug: "north-tripura", name: "North Tripura" },
  { slug: "chhota-udepur", name: "Chhota Udepur" },
  { slug: "jaunpur", name: "Jaunpur" },
  { slug: "madhepura", name: "Madhepura" },
  { slug: "vaishali-sector-6", name: "Vaishali Sector 6" },
  { slug: "jammu-and-kashmir", name: "Jammu and Kashmir" },
  { slug: "medchal-malkajgiri", name: "Medchal–Malkajgiri" },
  { slug: "tirunelveli", name: "Tirunelveli" },
  { slug: "karimganj", name: "Karimganj" },
  { slug: "wave-city-sector-3", name: "Wave City Sector 3" },
  { slug: "lower-subansiri", name: "Lower Subansiri" },
  { slug: "anjaw", name: "Anjaw" },
  { slug: "noida-sector-23", name: "Noida Sector 23" },
  { slug: "gurugram-sector-25", name: "Gurugram Sector 25" },
  { slug: "gurugram-sector-10", name: "Gurugram Sector 10" },
  { slug: "noida-sector-59", name: "Noida Sector 59" },
  { slug: "tawang", name: "Tawang" },
  { slug: "delhi-cantonment-bus-terminal", name: "Delhi Cantonment Bus Terminal" },
  { slug: "bargarh", name: "Bargarh" },
  { slug: "sivaganga", name: "Sivaganga" },
  { slug: "chamba", name: "Chamba" },
  { slug: "faridabad-sector-36", name: "Faridabad Sector 36" },
  { slug: "bhikaji-cama-place", name: "Bhikaji Cama Place" },
  { slug: "vaishali-sector-5", name: "Vaishali Sector 5" },
  { slug: "ramprastha-colony", name: "Ramprastha Colony" },
  { slug: "rajanna-sircilla", name: "Rajanna Sircilla" },
  { slug: "gurugram-sector-40", name: "Gurugram Sector 40" },
  { slug: "raj-nagar-sector-6", name: "Raj Nagar Sector 6" },
  { slug: "gorakhpur", name: "Gorakhpur" },
  { slug: "modinagar-railway-station", name: "Modinagar Railway Station" },
  { slug: "mahipalpur", name: "Mahipalpur" },
  { slug: "greater-noida-sector-tau-1", name: "Greater Noida Sector Tau 1" },
  { slug: "barabanki", name: "Barabanki" },
  { slug: "kirbi-place", name: "Kirbi Place" },
  { slug: "nehru-enclave", name: "Nehru Enclave" },
  { slug: "serchhip", name: "Serchhip" },
  { slug: "perambalur", name: "Perambalur" },
  { slug: "peren", name: "Peren" },
  { slug: "red-fort-lal-qila", name: "Red Fort (Lal Qila)" },
  { slug: "igi-airport-metro", name: "IGI Airport Metro" },
  { slug: "kamareddy", name: "Kamareddy" },
  { slug: "namakkal", name: "Namakkal" },
  { slug: "central-delhi", name: "Central Delhi" },
  { slug: "noida-sector-47", name: "Noida Sector 47" },
  { slug: "sanjay-nagar-sector-5", name: "Sanjay Nagar Sector 5" },
  { slug: "dhubri", name: "Dhubri" },
  { slug: "fatehabad", name: "Fatehabad" },
  { slug: "sundargarh", name: "Sundargarh" },
  { slug: "deoria", name: "Deoria" },
  { slug: "munger", name: "Munger" },
  { slug: "greater-noida-sector-gamma-1", name: "Greater Noida Sector Gamma 1" },
  { slug: "noida-sector-93", name: "Noida Sector 93" },
  { slug: "tronica-city-sector-a", name: "Tronica City Sector A" },
  { slug: "laxmi-nagar-bus-depot", name: "Laxmi Nagar Bus Depot" },
  { slug: "bathinda", name: "Bathinda" },
  { slug: "noida-sector-118", name: "Noida Sector 118" },
  { slug: "osmanabad", name: "Osmanabad" },
  { slug: "greater-noida-sector-zeta-1", name: "Greater Noida Sector Zeta 1" },
  { slug: "noida-sector-57", name: "Noida Sector 57" },
  { slug: "noida-sector-139", name: "Noida Sector 139" },
  { slug: "belgaum", name: "Belgaum" },
  { slug: "gurugram-sector-22b", name: "Gurugram Sector 22B" },
  { slug: "north-east-delhi", name: "North East Delhi" },
  { slug: "faridabad-sector-22", name: "Faridabad Sector 22" },
  { slug: "hindon-residential-area", name: "Hindon Residential Area" },
  { slug: "noida-sector-4", name: "Noida Sector 4" },
  { slug: "wave-city-sector-7", name: "Wave City Sector 7" },
  { slug: "lohardaga", name: "Lohardaga" },
  { slug: "vikaspuri", name: "Vikaspuri" },
  { slug: "greater-noida-sector-alpha-1", name: "Greater Noida Sector Alpha 1" },
  { slug: "kamrup-metropolitan", name: "Kamrup Metropolitan" },
  { slug: "greater-noida-sector-sigma-4", name: "Greater Noida Sector Sigma 4" },
  { slug: "mumbai", name: "Mumbai" },
  { slug: "gurugram-sector-11", name: "Gurugram Sector 11" },
  { slug: "sindhudurg", name: "Sindhudurg" },
  { slug: "basti", name: "Basti" },
  { slug: "morti-extension", name: "Morti Extension" },
  { slug: "morena", name: "Morena" },
  { slug: "bilaspur", name: "Bilaspur" },
  { slug: "noida-extension-sector-10", name: "Noida Extension Sector 10" },
  { slug: "jaisalmer", name: "Jaisalmer" },
  { slug: "gurugram-sector-38", name: "Gurugram Sector 38" },
  { slug: "narayanpur", name: "Narayanpur" },
  { slug: "firozabad", name: "Firozabad" },
  { slug: "jabalpur", name: "Jabalpur" },
  { slug: "bengaluru-rural", name: "Bengaluru Rural" },
  { slug: "thrissur", name: "Thrissur" },
  { slug: "kalahandi", name: "Kalahandi" },
  { slug: "chitradurga", name: "Chitradurga" },
  { slug: "bareilly", name: "Bareilly" },
  { slug: "mahasamund", name: "Mahasamund" },
  { slug: "shadipur-metro", name: "Shadipur Metro" },
  { slug: "sawai-madhopur", name: "Sawai Madhopur" },
  { slug: "noida-sector-108", name: "Noida Sector 108" },
  { slug: "kochi", name: "Kochi" },
  { slug: "noida-sector-101", name: "Noida Sector 101" },
  { slug: "noida-sector-24", name: "Noida Sector 24" },
  { slug: "kolasib", name: "Kolasib" },
  { slug: "vasundhara-sector-2", name: "Vasundhara Sector 2" },
  { slug: "shadipur", name: "Shadipur" },
  { slug: "pulwama", name: "Pulwama" },
  { slug: "noida-sector-94", name: "Noida Sector 94" },
  { slug: "anand-vihar-isbt", name: "Anand Vihar ISBT" },
  { slug: "indirapuram-abhay-khand-1", name: "Indirapuram Abhay Khand 1" },
  { slug: "yadgir", name: "Yadgir" },
  { slug: "dhar", name: "Dhar" },
  { slug: "majnu-ka-tilla", name: "Majnu Ka Tilla" },
  { slug: "tengnoupal", name: "Tengnoupal" },
  { slug: "khagaria", name: "Khagaria" },
  { slug: "jalaun", name: "Jalaun" },
  { slug: "shahdara", name: "Shahdara" },
  { slug: "noida-sector-2", name: "Noida Sector 2" },
  { slug: "gurugram-sector-2", name: "Gurugram Sector 2" },
  { slug: "kheri", name: "Kheri" },
  { slug: "simdega", name: "Simdega" },
  { slug: "koriya", name: "Koriya" },
  { slug: "gurugram-sector-34", name: "Gurugram Sector 34" },
  { slug: "okhla", name: "Okhla" },
  { slug: "uttarakhand", name: "Uttarakhand" },
  { slug: "mohan-nagar-industrial-area", name: "Mohan Nagar Industrial Area" },
  { slug: "kottayam", name: "Kottayam" },
  { slug: "jalpaiguri", name: "Jalpaiguri" },
  { slug: "murshidabad", name: "Murshidabad" },
  { slug: "sector-theta-3", name: "Sector Theta 3" },
  { slug: "dausa", name: "Dausa" },
  { slug: "kanpur", name: "Kanpur" },
  { slug: "faridabad", name: "Faridabad" },
  { slug: "noida-sector-148", name: "Noida Sector 148" },
  { slug: "howrah", name: "Howrah" },
  { slug: "kendujhar", name: "Kendujhar" },
  { slug: "malkangiri", name: "Malkangiri" },
  { slug: "siddipet", name: "Siddipet" },
  { slug: "jorhat", name: "Jorhat" },
  { slug: "shillong", name: "Shillong" },
  { slug: "gurugram-sector-9a", name: "Gurugram Sector 9A" },
  { slug: "raj-nagar-sector-3", name: "Raj Nagar Sector 3" },
  { slug: "tiruvannamalai", name: "Tiruvannamalai" },
  { slug: "naharlagun", name: "Naharlagun" },
  { slug: "gadchiroli", name: "Gadchiroli" },
  { slug: "baramulla", name: "Baramulla" },
  { slug: "patparganj", name: "Patparganj" },
  { slug: "jasola-vihar", name: "Jasola Vihar" },
  { slug: "sonitpur", name: "Sonitpur" },
  { slug: "ballarat", name: "Ballarat" },
  { slug: "hazaribagh", name: "Hazaribagh" },
  { slug: "north-garo-hills", name: "North Garo Hills" },
  { slug: "mohan-estate", name: "Mohan Estate" },
  { slug: "kingsway-camp", name: "Kingsway Camp" },
  { slug: "central-coast", name: "Central Coast" },
  { slug: "sirmaur", name: "Sirmaur" },
  { slug: "kheda", name: "Kheda" },
  { slug: "barmer", name: "Barmer" },
  { slug: "guntur", name: "Guntur" },
  { slug: "sector-64-indirapuram", name: "Sector 64 Indirapuram" },
  { slug: "faridabad-sector-33", name: "Faridabad Sector 33" },
  { slug: "krishna", name: "Krishna" },
  { slug: "hoshangabad", name: "Hoshangabad" },
  { slug: "north-24-parganas", name: "North 24 Parganas" },
  { slug: "cuttack", name: "Cuttack" },
  { slug: "parliament", name: "Parliament" },
  { slug: "najafgarh", name: "Najafgarh" },
  { slug: "etah", name: "Etah" },
  { slug: "indirapuram-shakti-khand-1", name: "Indirapuram Shakti Khand 1" },
  { slug: "new-delhi", name: "New Delhi" },
  { slug: "old-delhi-railway-station", name: "Old Delhi Railway Station" },
  { slug: "mon", name: "Mon" },
  { slug: "kurung-kumey", name: "Kurung Kumey" },
  { slug: "wollongong", name: "Wollongong" },
  { slug: "ramprastha", name: "Ramprastha" },
  { slug: "kaushambi", name: "Kaushambi" },
  { slug: "mancherial", name: "Mancherial" },
  { slug: "dibrugarh", name: "Dibrugarh" },
  { slug: "datia", name: "Datia" },
  { slug: "gujarat", name: "Gujarat" },
  { slug: "gurugram-sector-24", name: "Gurugram Sector 24" },
  { slug: "sirohi", name: "Sirohi" },
  { slug: "modinagar", name: "Modinagar" },
  { slug: "raj-nagar", name: "Raj Nagar" },
  { slug: "vasundhara-sector-9", name: "Vasundhara Sector 9" },
  { slug: "aditya-park-town", name: "Aditya Park Town" },
  { slug: "arjangarh", name: "Arjangarh" },
  { slug: "noida-sector-45", name: "Noida Sector 45" },
  { slug: "noida-sector-120", name: "Noida Sector 120" },
  { slug: "noida-sector-85", name: "Noida Sector 85" },
  { slug: "imphal-west", name: "Imphal West" },
  { slug: "ballabhgarh", name: "Ballabhgarh" },
  { slug: "devbhoomi-dwarka", name: "Devbhoomi Dwarka" },
  { slug: "sambalpur", name: "Sambalpur" },
  { slug: "bharat-nagar", name: "Bharat Nagar" },
  { slug: "ghaziabad-old-bus-stand", name: "Ghaziabad Old Bus Stand" },
  { slug: "shalimar-bagh", name: "Shalimar Bagh" },
  { slug: "gwalior", name: "Gwalior" },
  { slug: "tiruppur", name: "Tiruppur" },
  { slug: "ecotech-7", name: "Ecotech 7" },
  { slug: "noida-sector-135", name: "Noida Sector 135" },
  { slug: "rk-puram", name: "RK Puram" },
  { slug: "marigaon", name: "Marigaon" },
  { slug: "sector-13-vasundhara", name: "Sector 13 Vasundhara" },
  { slug: "mehsana", name: "Mehsana" },
  { slug: "najafgarh-depot", name: "Najafgarh Depot" },
  { slug: "faridabad-sector-20", name: "Faridabad Sector 20" },
  { slug: "indirapuram", name: "Indirapuram" },
  { slug: "pali", name: "Pali" },
  { slug: "balasore", name: "Balasore" },
  { slug: "noida-sector-76", name: "Noida Sector 76" },
  { slug: "faridkot", name: "Faridkot" },
  { slug: "kashmere-gate-isbt", name: "Kashmere Gate ISBT" },
  { slug: "tirupati", name: "Tirupati" },
  { slug: "moga", name: "Moga" },
  { slug: "mayapuri", name: "Mayapuri" },
  { slug: "siddharth-vihar-sector-2", name: "Siddharth Vihar Sector 2" },
  { slug: "noida-sector-30", name: "Noida Sector 30" },
  { slug: "ghaziabad", name: "Ghaziabad" },
  { slug: "raj-nagar-sector-5", name: "Raj Nagar Sector 5" },
  { slug: "hingoli", name: "Hingoli" },
  { slug: "balia", name: "Balia" },
  { slug: "sheohar", name: "Sheohar" },
  { slug: "kalkaji-mandir", name: "Kalkaji Mandir" },
  { slug: "kavi-nagar-sector-12", name: "Kavi Nagar Sector 12" },
  { slug: "bhadrak", name: "Bhadrak" },
  { slug: "mysuru", name: "Mysuru" },
  { slug: "rohtas", name: "Rohtas" },
  { slug: "kangra", name: "Kangra" },
  { slug: "noida-sector-126", name: "Noida Sector 126" },
  { slug: "noida-sector-136", name: "Noida Sector 136" },
  { slug: "noida-extension-sector-22d", name: "Noida Extension Sector 22D" },
  { slug: "vasant-kunj", name: "Vasant Kunj" },
  { slug: "faridabad-sector-16", name: "Faridabad Sector 16" },
  { slug: "victor-harbor-goolwa", name: "Victor Harbor–Goolwa" },
  { slug: "saran", name: "Saran" },
  { slug: "bardhaman", name: "Bardhaman" },
  { slug: "wave-city-sector-6", name: "Wave City Sector 6" },
  { slug: "moti-nagar", name: "Moti Nagar" },
  { slug: "rohini-sector-7", name: "Rohini Sector 7" },
  { slug: "kanniyakumari", name: "Kanniyakumari" },
  { slug: "palam-metro", name: "Palam Metro" },
  { slug: "chhapraula", name: "Chhapraula" },
  { slug: "noida-sector-67", name: "Noida Sector 67" },
  { slug: "ramanagara", name: "Ramanagara" },
  { slug: "kinnaur", name: "Kinnaur" },
  { slug: "aurangabad", name: "Aurangabad" },
  { slug: "dwarka-sector-21", name: "Dwarka Sector 21" },
  { slug: "ecotech-6", name: "Ecotech 6" },
  { slug: "vasundhara-sector-6", name: "Vasundhara Sector 6" },
  { slug: "morti-village", name: "Morti Village" },
  { slug: "geeta-colony", name: "Geeta Colony" },
  { slug: "faizabad", name: "Faizabad" },
  { slug: "noida-sector-5", name: "Noida Sector 5" },
  { slug: "sultanpur", name: "Sultanpur" },
  { slug: "gokalpuri", name: "Gokalpuri" },
  { slug: "greater-noida-sector-tau-2", name: "Greater Noida Sector Tau 2" },
  { slug: "maharajganj", name: "Maharajganj" },
  { slug: "mohan-nagar-chowk", name: "Mohan Nagar Chowk" },
  { slug: "nagaland", name: "Nagaland" },
  { slug: "fatehpur", name: "Fatehpur" },
  { slug: "crossings-republic-flora", name: "Crossings Republic Flora" },
  { slug: "dholpur", name: "Dholpur" },
  { slug: "faridabad-sector-24", name: "Faridabad Sector 24" },
  { slug: "noida-sector-130", name: "Noida Sector 130" },
  { slug: "hervey-bay", name: "Hervey Bay" },
  { slug: "kamrup", name: "Kamrup" },
  { slug: "ahmedabad", name: "Ahmedabad" },
  { slug: "noida-sector-52", name: "Noida Sector 52" },
  { slug: "yamuna-expressway-sector-27", name: "Yamuna Expressway Sector 27" },
  { slug: "gangtok", name: "Gangtok" },
  { slug: "noida-extension-sector-16b", name: "Noida Extension Sector 16B" },
  { slug: "noida-sector-53", name: "Noida Sector 53" },
  { slug: "indirapuram-nyay-khand-1", name: "Indirapuram Nyay Khand 1" },
  { slug: "defence-colony", name: "Defence Colony" },
  { slug: "thanjavur", name: "Thanjavur" },
  { slug: "ganderbal", name: "Ganderbal" },
  { slug: "pratap-vihar-sector-1", name: "Pratap Vihar Sector 1" },
  { slug: "herat", name: "Herat" },
  { slug: "lower-dibang-valley", name: "Lower Dibang Valley" },
  { slug: "anuppur", name: "Anuppur" },
  { slug: "patparganj-metro", name: "Patparganj Metro" },
  { slug: "faridabad-sector-21c", name: "Faridabad Sector 21C" },
  { slug: "meghalaya", name: "Meghalaya" },
  { slug: "faridabad-sector-28", name: "Faridabad Sector 28" },
  { slug: "noida-sector-41", name: "Noida Sector 41" },
  { slug: "gyan-khand-2", name: "Gyan Khand 2" },
  { slug: "tronica-city-sector-c", name: "Tronica City Sector C" },
  { slug: "shyam-park-main", name: "Shyam Park Main" },
  { slug: "noida-sector-50", name: "Noida Sector 50" },
  { slug: "jamshedpur", name: "Jamshedpur" },
  { slug: "bhagalpur", name: "Bhagalpur" },
  { slug: "noida-sector-133", name: "Noida Sector 133" },
  { slug: "sheikhpura", name: "Sheikhpura" },
  { slug: "champawat", name: "Champawat" },
  { slug: "bahraich", name: "Bahraich" },
  { slug: "kasaragod", name: "Kasaragod" },
  { slug: "singrauli", name: "Singrauli" },
  { slug: "faridabad-sector-29", name: "Faridabad Sector 29" },
  { slug: "chikkamagaluru", name: "Chikkamagaluru" },
  { slug: "noida-sector-82", name: "Noida Sector 82" },
  { slug: "newcastle-maitland", name: "Newcastle–Maitland" },
  { slug: "siwan", name: "Siwan" },
  { slug: "yavatmal", name: "Yavatmal" },
  { slug: "udhampur", name: "Udhampur" },
  { slug: "kalai", name: "Kalai" },
  { slug: "vasundhara-sector-11", name: "Vasundhara Sector 11" },
  { slug: "bangalore-rural", name: "Bangalore Rural" },
  { slug: "garhwa", name: "Garhwa" },
  { slug: "tronica-city-industrial-area", name: "Tronica City Industrial Area" },
  { slug: "nangloi", name: "Nangloi" },
  { slug: "noida-sector-10", name: "Noida Sector 10" },
  { slug: "solan", name: "Solan" },
  { slug: "noida-sector-104", name: "Noida Sector 104" },
  { slug: "noida-sector-123", name: "Noida Sector 123" },
  { slug: "fayzabad", name: "Fayzabad" },
  { slug: "daryaganj", name: "Daryaganj" },
  { slug: "noida-extension-sector-16c", name: "Noida Extension Sector 16C" },
  { slug: "rajniwas-marg", name: "Rajniwas Marg" },
  { slug: "kanpur-dehat", name: "Kanpur Dehat" },
  { slug: "dahod", name: "Dahod" },
  { slug: "wave-city-sector-4", name: "Wave City Sector 4" },
  { slug: "sector-xu-1", name: "Sector Xu 1" },
  { slug: "tapi", name: "Tapi" },
  { slug: "rithala", name: "Rithala" },
  { slug: "indirapuram-shakti-khand-4", name: "Indirapuram Shakti Khand 4" },
  { slug: "sector-eta-3", name: "Sector Eta 3" },
  { slug: "chander-nagar", name: "Chander Nagar" },
  { slug: "noida-sector-158", name: "Noida Sector 158" },
  { slug: "viluppuram", name: "Viluppuram" },
  { slug: "jirapur", name: "Jirapur" },
  { slug: "dharwad", name: "Dharwad" },
  { slug: "noida-sector-140", name: "Noida Sector 140" },
  { slug: "tinsukia", name: "Tinsukia" },
  { slug: "east-godavari", name: "East Godavari" },
  { slug: "bharat-city-township", name: "Bharat City Township" },
  { slug: "beed", name: "Beed" },
  { slug: "crossing-republik-mahagun-mascot", name: "Crossing Republik Mahagun Mascot" },
  { slug: "mainpuri", name: "Mainpuri" },
  { slug: "rajendra-place", name: "Rajendra Place" },
  { slug: "vasundhara-sector-5", name: "Vasundhara Sector 5" },
  { slug: "amrapali-dream-valley", name: "Amrapali Dream Valley" },
  { slug: "darrang", name: "Darrang" },
  { slug: "shalimar-city", name: "Shalimar City" },
  { slug: "suryapet", name: "Suryapet" },
  { slug: "noida-sector-90", name: "Noida Sector 90" },
  { slug: "crossing-republik-galleria-market", name: "Crossing Republik Galleria Market" },
  { slug: "banaskantha", name: "Banaskantha" },
  { slug: "sector-14-vasundhara", name: "Sector 14 Vasundhara" },
  { slug: "gurugram-sector-45", name: "Gurugram Sector 45" },
  { slug: "east-garo-hills", name: "East Garo Hills" },
  { slug: "ranchi", name: "Ranchi" },
  { slug: "sector-62-indirapuram", name: "Sector 62 Indirapuram" },
  { slug: "south-tripura", name: "South Tripura" },
  { slug: "mandawali-metro", name: "Mandawali Metro" },
  { slug: "kupwara", name: "Kupwara" },
  { slug: "sector-xu-3", name: "Sector Xu 3" },
  { slug: "gariaband", name: "Gariaband" },
  { slug: "noida-sector-32", name: "Noida Sector 32" },
  { slug: "idukki", name: "Idukki" },
  { slug: "chandel", name: "Chandel" },
  { slug: "kathua", name: "Kathua" },
  { slug: "noida-sector-147", name: "Noida Sector 147" },
  { slug: "mandsaur", name: "Mandsaur" },
  { slug: "meherpur", name: "Meherpur" },
  { slug: "noida-extension-sector-2", name: "Noida Extension Sector 2" },
  { slug: "noida-sector-111", name: "Noida Sector 111" },
  { slug: "dakshina-kannada", name: "Dakshina Kannada" },
  { slug: "knowledge-park-3", name: "Knowledge Park 3" },
  { slug: "indirapuram-abhay-khand-2", name: "Indirapuram Abhay Khand 2" },
  { slug: "chamarajanagar", name: "Chamarajanagar" },
  { slug: "kalkaji-mandir-metro", name: "Kalkaji Mandir Metro" },
  { slug: "ajnara-homes", name: "Ajnara Homes" },
  { slug: "phek", name: "Phek" },
  { slug: "daman", name: "Daman" },
  { slug: "sant-nagar", name: "Sant Nagar" },
  { slug: "ludhiana", name: "Ludhiana" },
  { slug: "mundka-industrial-area", name: "Mundka Industrial Area" },
  { slug: "noida-sector-141", name: "Noida Sector 141" },
  { slug: "yamuna-expressway-sector-26", name: "Yamuna Expressway Sector 26" },
  { slug: "wave-city-nh-24", name: "Wave City NH-24" },
  { slug: "noida-sector-11", name: "Noida Sector 11" },
  { slug: "kodagu", name: "Kodagu" },
  { slug: "techzone-v", name: "Techzone V" },
  { slug: "yamuna-expressway-sector-20", name: "Yamuna Expressway Sector 20" },
  { slug: "chhindwara", name: "Chhindwara" },
  { slug: "kaushambi-gda-flats", name: "Kaushambi GDA Flats" },
  { slug: "ramesh-nagar", name: "Ramesh Nagar" },
  { slug: "faridabad-sector-2", name: "Faridabad Sector 2" },
  { slug: "vizianagaram", name: "Vizianagaram" },
  { slug: "puri", name: "Puri" },
  { slug: "madhubani", name: "Madhubani" },
  { slug: "sri-ganganagar", name: "Sri Ganganagar" },
  { slug: "noida-sector-110", name: "Noida Sector 110" },
  { slug: "mehrauli-bus-depot", name: "Mehrauli Bus Depot" },
  { slug: "kollam", name: "Kollam" },
  { slug: "bangalore-urban", name: "Bangalore Urban" },
  { slug: "kirti-nagar-industrial-area", name: "Kirti Nagar Industrial Area" },
  { slug: "tripura", name: "Tripura" },
  { slug: "sukma", name: "Sukma" },
  { slug: "tura", name: "Tura" },
  { slug: "gadag", name: "Gadag" },
  { slug: "baghpat", name: "Baghpat" },
  { slug: "raj-nagar-sector-1", name: "Raj Nagar Sector 1" },
  { slug: "begusarai", name: "Begusarai" },
  { slug: "udalguri", name: "Udalguri" },
  { slug: "bahadurgarh-city", name: "Bahadurgarh City" },
  { slug: "gurugram-sector-14", name: "Gurugram Sector 14" },
  { slug: "nirman-vihar-bus-stop", name: "Nirman Vihar Bus Stop" },
  { slug: "west-kameng", name: "West Kameng" },
  { slug: "khordha", name: "Khordha" },
  { slug: "mukherjee-nagar", name: "Mukherjee Nagar" },
  { slug: "kanyakumari", name: "Kanyakumari" },
  { slug: "davanagere", name: "Davanagere" },
  { slug: "tarntaran", name: "Tarntaran" },
  { slug: "pushp-vihar", name: "Pushp Vihar" },
  { slug: "karbi-anglong", name: "Karbi Anglong" },
  { slug: "bankura", name: "Bankura" },
  { slug: "noida-sector-49", name: "Noida Sector 49" },
  { slug: "bulandshahr", name: "Bulandshahr" },
  { slug: "noida-sector-62", name: "Noida Sector 62" },
  { slug: "noida-extension-sector-16", name: "Noida Extension Sector 16" },
  { slug: "indirapuram-shakti-khand-2", name: "Indirapuram Shakti Khand 2" },
  { slug: "indirapuram-abhay-khand-3", name: "Indirapuram Abhay Khand 3" },
  { slug: "khammam", name: "Khammam" },
  { slug: "gt-karnal-road", name: "GT Karnal Road" },
  { slug: "bihar", name: "Bihar" },
  { slug: "seelampur", name: "Seelampur" },
  { slug: "sector-eta-2", name: "Sector Eta 2" },
  { slug: "narsinghpur", name: "Narsinghpur" },
  { slug: "ujjain", name: "Ujjain" },
  { slug: "civil-lines", name: "Civil Lines" },
  { slug: "south-east-delhi", name: "South East Delhi" },
  { slug: "noida-sector-51", name: "Noida Sector 51" },
  { slug: "botad", name: "Botad" },
  { slug: "ecotech-2", name: "Ecotech 2" },
  { slug: "shahjahanpur", name: "Shahjahanpur" },
  { slug: "jhansi", name: "Jhansi" },
  { slug: "papum-pare", name: "Papum Pare" },
  { slug: "namchi", name: "Namchi" },
  { slug: "modinagar-delhi-meerut-road", name: "Modinagar Delhi-Meerut Road" },
  { slug: "rajendra-nagar", name: "Rajendra Nagar" },
  { slug: "greater-noida-sector-sigma-1", name: "Greater Noida Sector Sigma 1" },
  { slug: "narayana-vihar", name: "Narayana Vihar" },
  { slug: "faridabad-sector-1", name: "Faridabad Sector 1" },
  { slug: "rupnagar", name: "Rupnagar" },
  { slug: "kavi-nagar-sector-11", name: "Kavi Nagar Sector 11" },
  { slug: "kurukshetra", name: "Kurukshetra" },
  { slug: "sanjay-nagar-sector-6", name: "Sanjay Nagar Sector 6" },
  { slug: "wave-city-sector-5", name: "Wave City Sector 5" },
  { slug: "tagore-garden", name: "Tagore Garden" },
  { slug: "sitamarhi", name: "Sitamarhi" },
  { slug: "noida-sector-117", name: "Noida Sector 117" },
  { slug: "sangareddy", name: "Sangareddy" },
  { slug: "warangal", name: "Warangal" },
  { slug: "rani-jhansi-road", name: "Rani Jhansi Road" },
  { slug: "noida-sector-36", name: "Noida Sector 36" },
  { slug: "sector-omicron-4", name: "Sector Omicron 4" },
  { slug: "govindpuram-sector-7", name: "Govindpuram Sector 7" },
  { slug: "jhilmil-industrial-area", name: "Jhilmil Industrial Area" },
  { slug: "karnal", name: "Karnal" },
  { slug: "welcome-metro-station", name: "Welcome Metro Station" },
  { slug: "vasundhara-sector-7", name: "Vasundhara Sector 7" },
  { slug: "west-tripura", name: "West Tripura" },
  { slug: "rajokri", name: "Rajokri" },
  { slug: "seoni", name: "Seoni" },
  { slug: "sector-phi-2", name: "Sector Phi 2" },
  { slug: "ramprastha-greens", name: "Ramprastha Greens" },
  { slug: "noida-sector-38a", name: "Noida Sector 38A" },
  { slug: "botanical-garden-metro", name: "Botanical Garden Metro" },
  { slug: "jharkhand", name: "Jharkhand" },
  { slug: "ghitorni", name: "Ghitorni" },
  { slug: "sikkim", name: "Sikkim" },
  { slug: "shyam-park-extension", name: "Shyam Park Extension" },
  { slug: "chittoor", name: "Chittoor" },
  { slug: "churachandpur", name: "Churachandpur" },
  { slug: "mayur-vihar-phase-iii", name: "Mayur Vihar Phase III" },
  { slug: "batla-house", name: "Batla House" },
  { slug: "noida-sector-160", name: "Noida Sector 160" },
  { slug: "lajpat-nagar", name: "Lajpat Nagar" },
  { slug: "nandgram", name: "Nandgram" },
  { slug: "wazirabad", name: "Wazirabad" },
  { slug: "udupi", name: "Udupi" },
  { slug: "shravasti", name: "Shravasti" },
  { slug: "noida-sector-29", name: "Noida Sector 29" },
  { slug: "mandla", name: "Mandla" },
  { slug: "raj-nagar-sector-2", name: "Raj Nagar Sector 2" },
  { slug: "noida-sector-73", name: "Noida Sector 73" },
  { slug: "goa", name: "Goa" },
  { slug: "tamenglong", name: "Tamenglong" },
  { slug: "jhajjar", name: "Jhajjar" },
  { slug: "ashok-vihar", name: "Ashok Vihar" },
  { slug: "dasna-nh-24", name: "Dasna NH-24" },
  { slug: "mahabubnagar", name: "Mahabubnagar" },
  { slug: "anantapur", name: "Anantapur" },
  { slug: "noida-sector-34", name: "Noida Sector 34" },
  { slug: "pragati-maidan", name: "Pragati Maidan" },
  { slug: "north-west-delhi", name: "North West Delhi" },
  { slug: "aizawl", name: "Aizawl" },
  { slug: "faridabad-sector-15a", name: "Faridabad Sector 15A" },
  { slug: "navsari", name: "Navsari" },
  { slug: "chengalpattu", name: "Chengalpattu" },
  { slug: "sitapur", name: "Sitapur" },
  { slug: "kalyanpuri-metro", name: "Kalyanpuri Metro" },
  { slug: "pratap-vihar-sector-2", name: "Pratap Vihar Sector 2" },
  { slug: "gulbarga", name: "Gulbarga" },
  { slug: "bharatpur", name: "Bharatpur" },
  { slug: "surendranagar", name: "Surendranagar" },
  { slug: "pondicherry", name: "Pondicherry" },
  { slug: "ecotech-extension", name: "Ecotech Extension" },
  { slug: "noida-sector-72", name: "Noida Sector 72" },
  { slug: "south-west-delhi", name: "South West Delhi" },
  { slug: "sheopur", name: "Sheopur" },
  { slug: "noida-sector-159", name: "Noida Sector 159" },
  { slug: "noida-sector-14", name: "Noida Sector 14" },
  { slug: "raj-nagar-extension", name: "Raj Nagar Extension" },
  { slug: "rohini-sector-11", name: "Rohini Sector 11" },
  { slug: "krishnagiri", name: "Krishnagiri" },
  { slug: "karkardooma", name: "Karkardooma" },
  { slug: "kapasheda-border", name: "Kapasheda Border" },
  { slug: "kovilpatti", name: "Kovilpatti" },
  { slug: "gurugram-sector-17", name: "Gurugram Sector 17" },
  { slug: "tronica-city-sector-e", name: "Tronica City Sector E" },
  { slug: "odisha", name: "Odisha" },
  { slug: "vidhan-sabha", name: "Vidhan Sabha" },
  { slug: "noida-sector-124", name: "Noida Sector 124" },
  { slug: "sector-zeta-5", name: "Sector Zeta 5" },
  { slug: "vaishali-sector-2", name: "Vaishali Sector 2" },
  { slug: "vaishali-metro", name: "Vaishali Metro" },
  { slug: "ramban", name: "Ramban" },
  { slug: "east-singhbhum", name: "East Singhbhum" },
  { slug: "erode", name: "Erode" },
  { slug: "techzone-iv", name: "Techzone IV" },
  { slug: "govindpuram-extension", name: "Govindpuram Extension" },
  { slug: "loni", name: "Loni" },
  { slug: "gyan-khand-3", name: "Gyan Khand 3" },
  { slug: "tehri-garhwal", name: "Tehri Garhwal" },
  { slug: "sanjay-nagar-sector-2", name: "Sanjay Nagar Sector 2" },
  { slug: "hanumangarh", name: "Hanumangarh" },
  { slug: "karawal-nagar", name: "Karawal Nagar" },
  { slug: "noida-extension-sector-18", name: "Noida Extension Sector 18" },
  { slug: "patel-nagar", name: "Patel Nagar" },
  { slug: "vasundhara-sector-8", name: "Vasundhara Sector 8" },
  { slug: "indirapuram-shakti-khand-3", name: "Indirapuram Shakti Khand 3" },
  { slug: "maharashtra", name: "Maharashtra" },
  { slug: "karauli", name: "Karauli" },
  { slug: "chattarpur", name: "Chattarpur" },
  { slug: "gurdaspur", name: "Gurdaspur" },
  { slug: "ghevra-metro", name: "Ghevra Metro" },
  { slug: "baksa", name: "Baksa" },
  { slug: "tarinkot", name: "Tarinkot" },
  { slug: "noida-sector-77", name: "Noida Sector 77" },
  { slug: "ri-bhoi", name: "Ri-Bhoi" },
  { slug: "noida-sector-153", name: "Noida Sector 153" },
  { slug: "behta-hazipur", name: "Behta Hazipur" },
  { slug: "vasundhara", name: "Vasundhara" },
  { slug: "dhaula-kuan", name: "Dhaula Kuan" },
  { slug: "longleng", name: "Longleng" },
  { slug: "sector-phi-1", name: "Sector Phi 1" },
  { slug: "noida-sector-105", name: "Noida Sector 105" },
  { slug: "delhi-gate", name: "Delhi Gate" },
  { slug: "govindpuram-sector-5", name: "Govindpuram Sector 5" },
  { slug: "noida-sector-1", name: "Noida Sector 1" },
  { slug: "faridabad-sector-7", name: "Faridabad Sector 7" },
  { slug: "bokaro", name: "Bokaro" },
  { slug: "palakkad", name: "Palakkad" },
  { slug: "paschim-medinipur", name: "Paschim Medinipur" },
  { slug: "noida-sector-64", name: "Noida Sector 64" },
  { slug: "barwani", name: "Barwani" },
  { slug: "chikkaballapur", name: "Chikkaballapur" },
  { slug: "pudukkottai", name: "Pudukkottai" },
  { slug: "faridabad-sector-18", name: "Faridabad Sector 18" },
  { slug: "west-bengal", name: "West Bengal" },
  { slug: "greater-noida-sector-pi-2", name: "Greater Noida Sector Pi 2" },
  { slug: "darshana", name: "Darshana" },
  { slug: "isbt-kashmere-gate", name: "ISBT Kashmere Gate" },
  { slug: "east-champaran", name: "East Champaran" },
  { slug: "noida-sector-119", name: "Noida Sector 119" },
  { slug: "jaypee-greens", name: "Jaypee Greens" },
  { slug: "chamoli", name: "Chamoli" },
  { slug: "boudh", name: "Boudh" },
  { slug: "noida-sector-20", name: "Noida Sector 20" },
  { slug: "agartala", name: "Agartala" },
  { slug: "vadodara", name: "Vadodara" },
  { slug: "fatehgarh-sahib", name: "Fatehgarh Sahib" },
  { slug: "hailakandi", name: "Hailakandi" },
  { slug: "noida-sector-125", name: "Noida Sector 125" },
  { slug: "latur", name: "Latur" },
  { slug: "noida-sector-3", name: "Noida Sector 3" },
  { slug: "greater-noida-sector-pi-1", name: "Greater Noida Sector Pi 1" },
  { slug: "nehrunagar-sector-2", name: "Nehrunagar Sector 2" },
  { slug: "vasundhara-sector-4", name: "Vasundhara Sector 4" },
  { slug: "vidisha", name: "Vidisha" },
  { slug: "deoghar", name: "Deoghar" },
  { slug: "chatra", name: "Chatra" },
  { slug: "nashik", name: "Nashik" },
  { slug: "kaithal", name: "Kaithal" },
  { slug: "indira-gandhi-international-airport-t3", name: "Indira Gandhi International Airport T3" },
  { slug: "techzone-1", name: "Techzone 1" },
  { slug: "kachchh", name: "Kachchh" },
  { slug: "mahendragarh", name: "Mahendragarh" },
  { slug: "tronica-city-sector-b", name: "Tronica City Sector B" },
  { slug: "kanker", name: "Kanker" },
  { slug: "noida-sector-63", name: "Noida Sector 63" },
  { slug: "sector-theta-1", name: "Sector Theta 1" },
  { slug: "mirzapur", name: "Mirzapur" },
  { slug: "hardoi", name: "Hardoi" },
  { slug: "vijayawada", name: "Vijayawada" },
  { slug: "khowai", name: "Khowai" },
  { slug: "vinod-nagar-metro", name: "Vinod Nagar Metro" },
  { slug: "rohtak", name: "Rohtak" },
  { slug: "niti-khand-4", name: "Niti Khand 4" },
  { slug: "kota", name: "Kota" },
  { slug: "dwarka-bus-depot", name: "Dwarka Bus Depot" },
  { slug: "faridabad-sector-19", name: "Faridabad Sector 19" },
  { slug: "chirag-delhi", name: "Chirag Delhi" },
  { slug: "pathankot", name: "Pathankot" },
  { slug: "kasna", name: "Kasna" },
  { slug: "nehrunagar-sector-1", name: "Nehrunagar Sector 1" },
  { slug: "noida-sector-91", name: "Noida Sector 91" },
  { slug: "galaxy-north-avenue", name: "Galaxy North Avenue" },
  { slug: "reasi", name: "Reasi" },
  { slug: "parbhani", name: "Parbhani" },
  { slug: "manipur", name: "Manipur" },
  { slug: "pratap-vihar-sector-3", name: "Pratap Vihar Sector 3" },
  { slug: "koderma", name: "Koderma" },
  { slug: "noida-extension-sector-30", name: "Noida Extension Sector 30" },
  { slug: "north-delhi", name: "North Delhi" },
  { slug: "palwal", name: "Palwal" },
  { slug: "raichur", name: "Raichur" },
  { slug: "jashpur", name: "Jashpur" },
  { slug: "shahdol", name: "Shahdol" },
  { slug: "pauri-garhwal", name: "Pauri Garhwal" },
  { slug: "noida-sector-70", name: "Noida Sector 70" },
  { slug: "noida-sector-88", name: "Noida Sector 88" },
  { slug: "siddharth-vihar-sector-3", name: "Siddharth Vihar Sector 3" },
  { slug: "paschim-vihar-west", name: "Paschim Vihar West" },
  { slug: "noida-sector-156", name: "Noida Sector 156" },
  { slug: "noida-sector-98", name: "Noida Sector 98" },
  { slug: "banda", name: "Banda" },
  { slug: "ecotech-1", name: "Ecotech 1" },
  { slug: "sector-mu-1", name: "Sector Mu 1" },
  { slug: "thane", name: "Thane" },
  { slug: "mandya", name: "Mandya" },
  { slug: "noida-sector-150", name: "Noida Sector 150" },
  { slug: "rajendra-nagar-extension", name: "Rajendra Nagar Extension" },
  { slug: "khunti", name: "Khunti" },
  { slug: "govindpuri", name: "Govindpuri" },
  { slug: "indraprastha", name: "Indraprastha" },
  { slug: "bidar", name: "Bidar" },
  { slug: "gurugram-sector-15", name: "Gurugram Sector 15" },
  { slug: "west-khasi-hills", name: "West Khasi Hills" },
  { slug: "hari-nagar", name: "Hari Nagar" },
  { slug: "agra", name: "Agra" },
  { slug: "moti-nagar-depot", name: "Moti Nagar Depot" },
  { slug: "nizamabad", name: "Nizamabad" },
  { slug: "india-gate", name: "India Gate" },
  { slug: "kerala", name: "Kerala" },
  { slug: "noida-sector-109", name: "Noida Sector 109" },
  { slug: "narmada", name: "Narmada" },
  { slug: "raj-nagar-extension-nh-58", name: "Raj Nagar Extension NH-58" },
  { slug: "joypurhat", name: "Joypurhat" },
  { slug: "crossings-republic-amrapali", name: "Crossings Republic Amrapali" },
  { slug: "azamgarh", name: "Azamgarh" },
  { slug: "pilibhit", name: "Pilibhit" },
  { slug: "pakur", name: "Pakur" },
  { slug: "bongaigaon", name: "Bongaigaon" },
  { slug: "guna", name: "Guna" },
  { slug: "ashok-nagar", name: "Ashok Nagar" },
  { slug: "vasundhara-enclave", name: "Vasundhara Enclave" },
  { slug: "hassan", name: "Hassan" },
  { slug: "west-delhi", name: "West Delhi" },
  { slug: "busselton", name: "Busselton" },
  { slug: "noida-sector-152", name: "Noida Sector 152" },
  { slug: "gumla", name: "Gumla" },
  { slug: "sector-omicron-3a", name: "Sector Omicron 3A" },
  { slug: "barpeta", name: "Barpeta" },
  { slug: "indirapuram-nyay-khand-2", name: "Indirapuram Nyay Khand 2" },
  { slug: "mau", name: "Mau" },
  { slug: "harda", name: "Harda" },
  { slug: "sangli", name: "Sangli" },
  { slug: "noida-sector-43", name: "Noida Sector 43" },
  { slug: "ecotech-3", name: "Ecotech 3" },
  { slug: "greater-noida-sector-sigma-3", name: "Greater Noida Sector Sigma 3" },
  { slug: "faridabad-sector-4", name: "Faridabad Sector 4" },
  { slug: "shivamogga", name: "Shivamogga" },
  { slug: "jamia-nagar", name: "Jamia Nagar" },
  { slug: "lakshmi-nagar-metro", name: "Lakshmi Nagar Metro" },
  { slug: "faridabad-sector-6", name: "Faridabad Sector 6" },
  { slug: "saharanpur", name: "Saharanpur" },
  { slug: "melbourne", name: "Melbourne" },
  { slug: "crossing-republik", name: "Crossing Republik" },
  { slug: "jind", name: "Jind" },
  { slug: "kaushambi-metro", name: "Kaushambi Metro" },
  { slug: "model-town", name: "Model Town" },
  { slug: "shajapur", name: "Shajapur" },
  { slug: "wanaparthy", name: "Wanaparthy" },
  { slug: "abhay-khand-1", name: "Abhay Khand 1" },
  { slug: "south-garo-hills", name: "South Garo Hills" },
  { slug: "loni-bhopura", name: "Loni Bhopura" },
  { slug: "crossing-republik-panchsheel-wellington", name: "Crossing Republik Panchsheel Wellington" },
  { slug: "nagaon", name: "Nagaon" },
  { slug: "jhilmil-colony", name: "Jhilmil Colony" },
  { slug: "kabul", name: "Kabul" },
  { slug: "buldhana", name: "Buldhana" },
  { slug: "kandahar", name: "Kandahar" },
  { slug: "kaimur", name: "Kaimur" },
  { slug: "noida-sector-7", name: "Noida Sector 7" },
  { slug: "shastri-park", name: "Shastri Park" },
  { slug: "margao", name: "Margao" },
  { slug: "peeragarhi", name: "Peeragarhi" },
  { slug: "paschim-vihar", name: "Paschim Vihar" },
  { slug: "yamuna-vihar-depot", name: "Yamuna Vihar Depot" },
  { slug: "sirsa", name: "Sirsa" },
  { slug: "vaishali-sector-8", name: "Vaishali Sector 8" },
  { slug: "noida-sector-69", name: "Noida Sector 69" },
  { slug: "punjabi-bagh", name: "Punjabi Bagh" },
  { slug: "noida-sector-129", name: "Noida Sector 129" },
  { slug: "siddharth-vihar-sector-1", name: "Siddharth Vihar Sector 1" },
  { slug: "kannur", name: "Kannur" },
  { slug: "delhi", name: "Delhi" },
  { slug: "faridabad-sector-37", name: "Faridabad Sector 37" },
  { slug: "baba-colony", name: "Baba Colony" },
  { slug: "pitampura", name: "Pitampura" },
  { slug: "indira-gandhi-indoor-stadium", name: "Indira Gandhi Indoor Stadium" },
  { slug: "gyan-khand-4", name: "Gyan Khand 4" },
  { slug: "ghaziabad-bus-stand", name: "Ghaziabad Bus Stand" },
  { slug: "raipur", name: "Raipur" },
  { slug: "noida-sector-75", name: "Noida Sector 75" },
  { slug: "dwarka-sector-10-metro", name: "Dwarka Sector 10 Metro" },
  { slug: "samba", name: "Samba" },
  { slug: "nanded", name: "Nanded" },
  { slug: "tonk", name: "Tonk" },
  { slug: "noida-sector-128", name: "Noida Sector 128" },
  { slug: "govindpuram-sector-4", name: "Govindpuram Sector 4" },
  { slug: "noida-sector-27", name: "Noida Sector 27" },
  { slug: "noida-sector-93a", name: "Noida Sector 93A" },
  { slug: "noida-sector-25", name: "Noida Sector 25" },
  { slug: "noida-sector-95", name: "Noida Sector 95" },
  { slug: "lakhimpur-kheri", name: "Lakhimpur Kheri" },
  { slug: "faridabad-sector-13", name: "Faridabad Sector 13" },
  { slug: "sri-potti-sriramulu-nellore", name: "Sri Potti Sriramulu Nellore" },
  { slug: "preet-vihar", name: "Preet Vihar" },
  { slug: "jalna", name: "Jalna" },
  { slug: "khandwa", name: "Khandwa" },
  { slug: "thoothukudi", name: "Thoothukudi" },
  { slug: "bikaner", name: "Bikaner" },
  { slug: "sanjay-nagar-sector-3", name: "Sanjay Nagar Sector 3" },
  { slug: "silchar", name: "Silchar" },
  { slug: "nand-nagri", name: "Nand Nagri" },
  { slug: "kandhamal", name: "Kandhamal" },
  { slug: "kapurthala", name: "Kapurthala" },
  { slug: "trilokpuri-metro", name: "Trilokpuri Metro" },
  { slug: "gurugram-sector-41", name: "Gurugram Sector 41" },
  { slug: "gurugram-sector-44", name: "Gurugram Sector 44" },
  { slug: "sikar", name: "Sikar" },
  { slug: "bhiwani", name: "Bhiwani" },
  { slug: "gurugram-sector-8", name: "Gurugram Sector 8" },
  { slug: "punjab", name: "Punjab" },
  { slug: "gurugram-sector-43", name: "Gurugram Sector 43" },
  { slug: "dundahera", name: "Dundahera" },
  { slug: "balaghat", name: "Balaghat" },
  { slug: "wayanad", name: "Wayanad" },
  { slug: "noida-sector-106", name: "Noida Sector 106" },
  { slug: "knowledge-park-5", name: "Knowledge Park 5" },
  { slug: "imphal-east", name: "Imphal East" },
  { slug: "gurugram-sector-12", name: "Gurugram Sector 12" },
  { slug: "okhla-bird-sanctuary", name: "Okhla Bird Sanctuary" },
  { slug: "lalitpur", name: "Lalitpur" },
  { slug: "garhwal-pauri-garhwal", name: "Garhwal (Pauri Garhwal)" },
  { slug: "vaishali", name: "Vaishali" },
  { slug: "chittagong", name: "Chittagong" },
  { slug: "rajnandgaon", name: "Rajnandgaon" },
  { slug: "noida-extension-sector-25", name: "Noida Extension Sector 25" },
  { slug: "new-friends-colony", name: "New Friends Colony" },
  { slug: "noida-sector-56", name: "Noida Sector 56" },
  { slug: "greater-noida-sector-delta-1", name: "Greater Noida Sector Delta 1" },
  { slug: "noida-extension-sector-4", name: "Noida Extension Sector 4" },
  { slug: "salem", name: "Salem" },
  { slug: "paschim-vihar-east", name: "Paschim Vihar East" },
  { slug: "dwarka-sector-9", name: "Dwarka Sector 9" },
  { slug: "rampur", name: "Rampur" },
  { slug: "bijapur", name: "Bijapur" },
  { slug: "sector-12-vasundhara", name: "Sector 12 Vasundhara" },
  { slug: "gazipur", name: "Gazipur" },
  { slug: "malviya-nagar", name: "Malviya Nagar" },
  { slug: "noida-sector-86", name: "Noida Sector 86" },
  { slug: "rohini-sector-13", name: "Rohini Sector 13" },
  { slug: "wave-city-harmony-floors", name: "Wave City Harmony Floors" },
  { slug: "rohini-sector-3", name: "Rohini Sector 3" },
  { slug: "rockhampton", name: "Rockhampton" },
  { slug: "vikarabad", name: "Vikarabad" },
  { slug: "greater-noida-sector-beta-1", name: "Greater Noida Sector Beta 1" },
  { slug: "burhanpur", name: "Burhanpur" },
  { slug: "muzaffarnagar", name: "Muzaffarnagar" },
  { slug: "uttara-kannada", name: "Uttara Kannada" },
  { slug: "janakpuri", name: "Janakpuri" },
  { slug: "noida-sector-80", name: "Noida Sector 80" },
  { slug: "dilshad-garden-depot", name: "Dilshad Garden Depot" },
  { slug: "yamuna-expressway-sector-25", name: "Yamuna Expressway Sector 25" },
  { slug: "noida-city-center-metro", name: "Noida City Center Metro" },
  { slug: "panna", name: "Panna" },
  { slug: "indira-gandhi-international-airport-t1", name: "Indira Gandhi International Airport T1" },
  { slug: "gurugram-huda-city-center", name: "Gurugram HUDA City Center" },
  { slug: "janjgir-champa", name: "Janjgir-Champa" },
  { slug: "ballari", name: "Ballari" },
  { slug: "dwarka-mor-metro", name: "Dwarka Mor Metro" },
  { slug: "noida-sector-146", name: "Noida Sector 146" },
  { slug: "moradabad", name: "Moradabad" },
  { slug: "shastri-nagar", name: "Shastri Nagar" },
  { slug: "uttam-nagar", name: "Uttam Nagar" },
  { slug: "rewa", name: "Rewa" },
  { slug: "jhunjhunu", name: "Jhunjhunu" },
  { slug: "tuensang", name: "Tuensang" },
  { slug: "crossing-republik-paramount-symphony", name: "Crossing Republik Paramount Symphony" },
  { slug: "saiha", name: "Saiha" },
  { slug: "sarai-kale-khan-isbt", name: "Sarai Kale Khan ISBT" },
  { slug: "kozhikode", name: "Kozhikode" },
  { slug: "aiims", name: "AIIMS" },
  { slug: "sector-zeta-3", name: "Sector Zeta 3" },
  { slug: "noida-sector-16a", name: "Noida Sector 16A" },
  { slug: "okhla-nsic", name: "Okhla NSIC" },
  { slug: "hathras", name: "Hathras" },
  { slug: "abhay-khand-2", name: "Abhay Khand 2" },
  { slug: "tughlaqabad", name: "Tughlaqabad" },
  { slug: "bastar", name: "Bastar" },
  { slug: "uttar-dinajpur", name: "Uttar Dinajpur" },
  { slug: "bagerhat", name: "Bagerhat" },
  { slug: "east-siang", name: "East Siang" },
  { slug: "bageshwar", name: "Bageshwar" },
  { slug: "warangal-rural", name: "Warangal (Rural)" },
  { slug: "dhule", name: "Dhule" },
  { slug: "warangal-urban", name: "Warangal (Urban)" },
  { slug: "mount-gambier", name: "Mount Gambier" },
  { slug: "narayanganj", name: "Narayanganj" },
  { slug: "mahe", name: "Mahe" },
  { slug: "raebareli", name: "Raebareli" },
  { slug: "bangalore", name: "Bangalore" },
  { slug: "faridabad-sector-10", name: "Faridabad Sector 10" },
  { slug: "nyay-khand-3", name: "Nyay Khand 3" },
  { slug: "masuri", name: "Masuri" },
  { slug: "faridabad-sector-23", name: "Faridabad Sector 23" },
  { slug: "kavi-nagar", name: "Kavi Nagar" },
  { slug: "noida-extension-sector-20", name: "Noida Extension Sector 20" },
  { slug: "kakinada", name: "Kakinada" },
  { slug: "nabadwip", name: "Nabadwip" },
  { slug: "knowledge-park-4", name: "Knowledge Park 4" },
  { slug: "arunachal-pradesh", name: "Arunachal Pradesh" },
  { slug: "rangareddy", name: "Rangareddy" },
  { slug: "palamu", name: "Palamu" },
  { slug: "shalimar-garden-ext-2", name: "Shalimar Garden Ext 2" },
  { slug: "naraina-vihar", name: "Naraina Vihar" },
  { slug: "nagpur", name: "Nagpur" },
  { slug: "kushinagar", name: "Kushinagar" },
  { slug: "rajouri", name: "Rajouri" },
  { slug: "panaji", name: "Panaji" },
  { slug: "noida-sector-48", name: "Noida Sector 48" },
  { slug: "malappuram", name: "Malappuram" },
  { slug: "kanpur-nagar", name: "Kanpur Nagar" },
  { slug: "connaught-place", name: "Connaught Place" },
  { slug: "tikamgarh", name: "Tikamgarh" },
  { slug: "dhemaji", name: "Dhemaji" },
  { slug: "wardha", name: "Wardha" },
  { slug: "noida-sector-46", name: "Noida Sector 46" },
  { slug: "vaishali-sector-1", name: "Vaishali Sector 1" },
  { slug: "ramakrishna-ashram-marg", name: "Ramakrishna Ashram Marg" },
  { slug: "jamtara", name: "Jamtara" },
  { slug: "nabarangpur", name: "Nabarangpur" },
  { slug: "najafgarh-bus-stand", name: "Najafgarh Bus Stand" },
  { slug: "kannauj", name: "Kannauj" },
  { slug: "yamunanagar", name: "Yamunanagar" },
  { slug: "azadpur", name: "Azadpur" },
  { slug: "cuddalore", name: "Cuddalore" },
  { slug: "theni", name: "Theni" },
  { slug: "jama-masjid", name: "Jama Masjid" },
  { slug: "sector-eta-1", name: "Sector Eta 1" },
  { slug: "greater-noida-sector-sigma-2", name: "Greater Noida Sector Sigma 2" },
  { slug: "morbi", name: "Morbi" },
  { slug: "neemuch", name: "Neemuch" },
  { slug: "noida-sector-142", name: "Noida Sector 142" },
  { slug: "firozpur", name: "Firozpur" },
  { slug: "dharmapuri", name: "Dharmapuri" },
  { slug: "supreme-court", name: "Supreme Court" },
  { slug: "lakshadweep", name: "Lakshadweep" },
  { slug: "katihar", name: "Katihar" },
  { slug: "bhajanpura", name: "Bhajanpura" },
  { slug: "noida-extension-sector-12", name: "Noida Extension Sector 12" },
  { slug: "rajouri-garden", name: "Rajouri Garden" },
  { slug: "karnataka", name: "Karnataka" },
  { slug: "mandawali-fazalpur", name: "Mandawali Fazalpur" },
  { slug: "muradnagar-main-market", name: "Muradnagar Main Market" },
  { slug: "loni-tronica-city", name: "Loni Tronica City" },
  { slug: "shankar-vihar", name: "Shankar Vihar" },
  { slug: "rayagada", name: "Rayagada" },
  { slug: "wave-city-sector-1", name: "Wave City Sector 1" },
  { slug: "greater-noida-sector-delta-2", name: "Greater Noida Sector Delta 2" },
  { slug: "niti-khand-3", name: "Niti Khand 3" },
  { slug: "mahoba", name: "Mahoba" },
  { slug: "gajapati", name: "Gajapati" },
  { slug: "faridabad-sector-14", name: "Faridabad Sector 14" },
  { slug: "gautam-buddha-nagar", name: "Gautam Buddha Nagar" },
  { slug: "chhatarpur", name: "Chhatarpur" },
  { slug: "gurugram-sector-5", name: "Gurugram Sector 5" },
  { slug: "vaishali-sector-7", name: "Vaishali Sector 7" },
  { slug: "chitrakoot", name: "Chitrakoot" },
  { slug: "kalindi-kunj", name: "Kalindi Kunj" },
  { slug: "raj-nagar-sector-7", name: "Raj Nagar Sector 7" },
  { slug: "thiruvallur", name: "Thiruvallur" },
  { slug: "greater-noida-sector-zeta-2", name: "Greater Noida Sector Zeta 2" },
  { slug: "greater-noida-sector-delta-3", name: "Greater Noida Sector Delta 3" },
  { slug: "haveri", name: "Haveri" },
  { slug: "sanjay-nagar-sector-1", name: "Sanjay Nagar Sector 1" },
  { slug: "raisen", name: "Raisen" },
  { slug: "dadra-and-nagar-haveli", name: "Dadra & Nagar Haveli" },
  { slug: "gurugram-iffco-chowk", name: "Gurugram IFFCO Chowk" },
  { slug: "akshardham-temple", name: "Akshardham Temple" },
  { slug: "kendrapara", name: "Kendrapara" },
  { slug: "karol-bagh", name: "Karol Bagh" },
  { slug: "bhojpur", name: "Bhojpur" },
  { slug: "pratapgarh", name: "Pratapgarh" },
  { slug: "noida-sector-74", name: "Noida Sector 74" },
  { slug: "sector-omicron-1a", name: "Sector Omicron 1A" },
  { slug: "gurugram-sector-6", name: "Gurugram Sector 6" },
  { slug: "faridabad-sector-21a", name: "Faridabad Sector 21A" },
  { slug: "andhra-pradesh", name: "Andhra Pradesh" },
  { slug: "west-godavari", name: "West Godavari" },
  { slug: "banaras", name: "Banaras" },
  { slug: "rohini-sector-18", name: "Rohini Sector 18" },
  { slug: "rahanpur", name: "Rahanpur" },
  { slug: "noida-sector-81", name: "Noida Sector 81" },
  { slug: "noida-sector-143a", name: "Noida Sector 143A" },
  { slug: "preet-vihar-metro", name: "Preet Vihar Metro" },
];

export const locationData: LocationData[] = rawLocations.map((loc) => ({
  slug: loc.slug,
  name: loc.name,
  title: getCityMetaTitle(loc.name),
  description: getCityMetaDescription(loc.name),
}));

const locationBySlugMap = new Map<string, LocationData>();
for (const loc of locationData) {
  locationBySlugMap.set(loc.slug, loc);
}

export function getLocationBySlug(slug: string): LocationData | undefined {
  return locationBySlugMap.get(slug);
}
